/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2026-06-03 22:30:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.oscarEncounter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.apache.commons.lang.StringUtils;
import oscar.oscarEncounter.pageUtil.NavBarDisplayDAO;
import oscar.util.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.Calendar;
import java.io.IOException;
import org.oscarehr.util.SpringUtils;
import com.quatro.dao.security.SecobjprivilegeDao;
import com.quatro.model.security.Secobjprivilege;
import java.util.List;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import org.oscarehr.common.model.SystemPreferences;
import org.oscarehr.common.dao.SystemPreferencesDao;
import org.apache.commons.lang.StringEscapeUtils;
import org.owasp.encoder.Encode;

public final class LeftNavBarDisplay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    public String getBackgroundColor(NavBarDisplayDAO dao){
        if ( dao.hasHeadingColour()){
           return  "background-color: #"+dao.getHeadingColour()+";";
        }
        return "";
    }

    public int display(ArrayList<NavBarDisplayDAO.Item>items, int numToDisplay, int numDisplayed, String reloadUrl, boolean xpanded, int numItems, StringBuilder js, int displayThreshold, String divReloadUrl, String cmd, javax.servlet.http.HttpServletRequest request, javax.servlet.jsp.JspWriter out ) throws IOException {
        String stripe,colour,bgColour;
        String imgName;
        String dateFormat = "dd-MMM-yyyy";
        Pattern pattern = Pattern.compile("'([^']*)'");


        String divReloadInfo;
        numToDisplay -= numDisplayed;

        int total = items.size() < numToDisplay ? items.size() : numToDisplay;
        int j;
        int curNum = numDisplayed;
        for(j = 0 ; j< total; ++j ) {
                NavBarDisplayDAO.Item item = items.get(j);
                colour = item.getColour().equals("") ? "" : "color: " + item.getColour() + ";";
                bgColour = item.getBgColour().equals("") ? "background-color: #f3f3f3;" : "background-color: " + item.getBgColour() + ";";
                String dateColour = "background-color: white;";
                bgColour = "";
                if (!item.getBgColour().isEmpty()) {
                  bgColour = "background-color: " + item.getBgColour() + ";";
                  dateColour = bgColour;
                } else if ((j % 2) == 0) {
                  bgColour = "background-color: #f3f3f3;";
                  dateColour = bgColour;
                }
                out.println("<li style=\"overflow: hidden; clear:both; position:relative; display:block; white-space:nowrap; "
                        + bgColour + "\">");

                if( curNum == 0 && xpanded ) {
                    imgName = "img" + request.getAttribute("navbarName") + curNum;
                    out.println("<a href='#' onclick=\"return false;\" style='text-decoration:none; width:7px; z-index: 100; "+dateColour+" position:relative; margin: 0px; padding-bottom: 0px;  vertical-align: bottom; display: inline; float: right; clear:both;'><img id='" + imgName + "' src='" + request.getContextPath() + "/oscarMessenger/img/collapse.gif'/>&nbsp;&nbsp;</a>");
                    js.append("imgfunc['" + imgName + "'] = clickListDisplay.bindAsEventListener(obj,'" + request.getAttribute("navbarName") + "', '" + displayThreshold + "');" );
                    js.append("Element.observe($('" + imgName + "'), 'click', imgfunc['" + imgName + "']);");
                }else if( j == (numToDisplay-1) && xpanded ) {
                    imgName = "img" + request.getAttribute("navbarName") + curNum;
                    out.println("<a href='#' onclick=\"return false;\" style='text-decoration:none; width:7px; z-index: 100; "+dateColour+" position:relative; margin: 0px; padding-bottom: 0px;  vertical-align: bottom; display: inline; float: right; clear:both;'><img id='" + imgName + "' src='" + request.getContextPath() + "/oscarMessenger/img/collapse.gif'/>&nbsp;&nbsp;</a>");
                    js.append("imgfunc['" + imgName + "'] = clickListDisplay.bindAsEventListener(obj,'" + request.getAttribute("navbarName") + "', '" + displayThreshold + "');" );
                    js.append("Element.observe($('" + imgName + "'), 'click', imgfunc['" + imgName + "']);");
                }else if( j == (numToDisplay-1) && numItems > (curNum+1) ) {
                    imgName = "img" + request.getAttribute("navbarName") + curNum;
                    out.println("<a href='#' onclick=\"return false;\" title='" + String.valueOf(numItems - j - 1) + " more items' style=' text-decoration:none; width:7px; z-index: 100; "+dateColour+" position:relative; margin: 0px; padding-bottom: 0px;  vertical-align: bottom; display: inline; float: right; clear:both;'><img id='" + imgName +  "' src='" + request.getContextPath() + "/oscarEncounter/graphics/expand.gif'/>&nbsp;&nbsp;</a>");
                    js.append("imgfunc['" + imgName + "'] = clickLoadDiv.bindAsEventListener(obj,'" + request.getAttribute("navbarName") + "','" + reloadUrl + "');" );
                    js.append("Element.observe($('" + imgName + "'), 'click', imgfunc['" + imgName + "']);");
                }else{
                    out.println("<a border=0 style='text-decoration:none; width:7px; z-index: 100; "+dateColour+" position:relative; margin: 0px; padding-bottom: 0px;  vertical-align: bottom; display: inline; float: right; clear:both;'><img  id='img" + request.getAttribute("navbarName") + curNum + "' src='" + request.getContextPath() + "/images/clear.gif'/>&nbsp;&nbsp;</a>");
                }
                ++curNum;

                out.println("<span style=\" z-index: 1; position:absolute; margin-right:10px; width:90%; overflow:hidden;  height:1.2em; white-space:nowrap; float:left; text-align:left; \">");
				String url = item.getURL();
				//This should be done in the display classes but I'll keep it here for future reference
				//url = StringUtils.replaceEach(url, new String[] {"'","\\\""}, new String[] {"\'","\\\""});
                if( item.isURLJavaScript() ) {
                    divReloadInfo = trackWindowString(url, divReloadUrl, cmd, pattern);
                	out.println("<a class='links' style='" + colour + "' onmouseover=\"this.className='linkhover'\" onmouseout=\"this.className='links'\" href='#' onclick=\"" + divReloadInfo + url + "\" title='" + item.getLinkTitle() + "'>");
                }
                else {
                	out.println("<a class='links' style='" + colour + "' onmouseover=\"this.className='linkhover'\" onmouseout=\"this.className='links'\" href=\"" + url + "\" title='" + item.getLinkTitle() + "' target=\"_blank\">");
                }
                out.println(item.getTitle());
                out.println("</a>");
                out.println("</span>");

                if( item.getDate() != null ) {
                    out.println("<span style=\"z-index: 100; "+dateColour+" overflow:hidden;   position:relative; height:1.2em; white-space:nowrap; float:right; text-align:right;\">");

                    if( item.isURLJavaScript() ) {
                		divReloadInfo = trackWindowString(url, divReloadUrl, cmd, pattern);
                    	out.println("...<a class='links' style='margin-right: 2px;" + colour + "' onmouseover=\"this.className='linkhover'\" onmouseout=\"this.className='links'\" href='#' onclick=\"" + divReloadInfo + url + "\" title='" + item.getLinkTitle() + "'>");
                    }
                    else {
                    	out.println("...<a class='links' style='margin-right: 2px;" + colour + "' onmouseover=\"this.className='linkhover'\" onmouseout=\"this.className='links'\" href=\"" + url + "\" title='" + item.getLinkTitle() + "' target=\"_blank\">");
                    }

                    if(item.getValue() != null && !item.getValue().trim().equals("")){
                        out.println(item.getValue());
                    }
                    out.println(DateUtils.getDate(item.getDate(), dateFormat, request.getLocale()));
                    out.println("</a>");
                    out.println("</span>");
                }
                out.println("</li>");
         }

         return j;
    }

    public int displayRXList(ArrayList<NavBarDisplayDAO.Item>items, int numToDisplay, int numDisplayed,
            String reloadUrl, boolean xpanded, int numItems, StringBuilder js, int displayThreshold,
            String divReloadUrl, String cmd, javax.servlet.http.HttpServletRequest request,
            javax.servlet.jsp.JspWriter out ) throws IOException {
        String stripe,colour,bgColour;
        String imgName;
        String dateFormat = "dd-MMM-yyyy";
        Pattern pattern = Pattern.compile("'([^']*)'");

        String divReloadInfo;
        numToDisplay -= numDisplayed;
        int total = items.size() < numToDisplay ? items.size() : numToDisplay;
        int j;
        int curNum = numDisplayed;
            boolean isConsent = request.getAttribute("consent") != null;
        for (j = 0 ; j< total; ++j) {
            NavBarDisplayDAO.Item item = items.get(j);
            colour = item.getColour().equals("") ? "" : "color: " + item.getColour() + ";";
            bgColour = item.getBgColour().equals("") ? "background-color: #f3f3f3;" : "background-color: " + item.getBgColour() + ";";
            String dateColour = "background-color: white;";

            if ((j % 2) == 0) {
                stripe = "style=\"overflow: hidden; clear:both; position:relative; display:block; white-space:nowrap; " + bgColour + "\"";
                dateColour = bgColour;
            } else {
                stripe = "style=\"overflow: hidden; clear:both; position:relative; display:block; white-space:nowrap; \"";
            }
            out.println("<li " + stripe + ">");

            if (curNum == 0 && xpanded) {
                imgName = "img" + (isConsent? "consent" : request.getAttribute("navbarName")) + curNum;
                out.println(
                    "<a href='#' onclick=\"return false;\" style='text-decoration:none; width:7px; z-index: 100; "
                    + dateColour
                    + " position:relative; margin: 0px; padding-bottom: 0px; vertical-align: bottom; display: inline; float: right; clear:both;'><img id='"
                    + imgName + "' src='" + request.getContextPath()
                    + "/oscarMessenger/img/collapse.gif'/>&nbsp;&nbsp;</a>");

                js.append("imgfunc['" + imgName + "'] = clickListDisplay.bindAsEventListener(obj,'" + (isConsent? "consent" : request.getAttribute("navbarName")) + "', '" + displayThreshold + "');" );
                js.append("Element.observe($('" + imgName + "'), 'click', imgfunc['" + imgName + "']);");
            } else
                if (j == (numToDisplay-1) && xpanded) {
                    imgName = "img" + (isConsent? "consent" : request.getAttribute("navbarName")) + curNum;
                    out.println(
                        "<a href='#' onclick=\"return false;\" style='text-decoration:none; width:7px; z-index: 100; "
                        + dateColour
                        + " position:relative; margin: 0px; padding-bottom: 0px;  vertical-align: bottom; display: inline; float: right; clear:both;'><img id='"
                        + imgName + "' src='" + request.getContextPath()
                        + "/oscarMessenger/img/collapse.gif'/>&nbsp;&nbsp;</a>");

                    js.append("imgfunc['" + imgName + "'] = clickListDisplay.bindAsEventListener(obj,'" + (isConsent? "consent" : request.getAttribute("navbarName")) + "', '" + displayThreshold + "');" );
                    js.append("Element.observe($('" + imgName + "'), 'click', imgfunc['" + imgName + "']);");
            } else
                if (j == (numToDisplay-1) && numItems > (curNum+1)) {
                    if (isConsent) {
                        reloadUrl = reloadUrl.substring(0, reloadUrl.indexOf("cmd")) + "cmd=consent";
                    }
                    imgName = "img" + (isConsent ? "consent" : request.getAttribute("navbarName")) + curNum;
                    out.println(
                        "<a href='#' onclick=\"return false;\" title='" + String.valueOf(numItems - j - 1)
                        + " more items' style=' text-decoration:none; width:7px; z-index: 100; " + dateColour
                        + " position:relative; margin: 0px; padding-bottom: 0px;  vertical-align: bottom; display: inline; float: right; clear:both;'><img id='"
                        + imgName + "' src='" + request.getContextPath()
                        + "/oscarEncounter/graphics/expand.gif'/>&nbsp;&nbsp;</a>");

                    js.append("imgfunc['" + imgName + "'] = clickLoadDiv.bindAsEventListener(obj,'" + (isConsent ? "consent" : request.getAttribute("navbarName")) + "','" + reloadUrl + "');" );
                    js.append("Element.observe($('" + imgName + "'), 'click', imgfunc['" + imgName + "']);");
            } else {
                out.println(
                    "<a border=0 style='text-decoration:none; width:7px; z-index: 100; " + dateColour
                    + " position:relative; margin: 0px; padding-bottom: 0px;  vertical-align: bottom; display: inline; float: right; clear:both;'><img  id='img"
                    + (isConsent? "consent" : request.getAttribute("navbarName")) + curNum
                    + "' src='" + request.getContextPath() + "/images/clear.gif'/>&nbsp;&nbsp;</a>");
            }

            ++curNum;

            out.println(
                "<span style=\" z-index: 1; position:absolute; margin-right:10px; width:90%; overflow:hidden; height:1.2em; white-space:nowrap; float:left; text-align:left; \">");

            SystemPreferencesDao systemPreferencesDao = SpringUtils.getBean(SystemPreferencesDao.class);
            SystemPreferences represcribeName = systemPreferencesDao.findPreferenceByName("represcribe_name");
            String represcribeNameString = represcribeName != null?  represcribeName.getValue() : "";
            if (represcribeNameString.equalsIgnoreCase("ReRx")) {
                out.println(
                    "<a class='links>' href='#' onclick=\"rePrescribe('" + item.getValue()
                    + "');writeNewNoteSimple('\\nRe-prescribe: " + StringEscapeUtils.escapeJavaScript(item.getTitle()) + "');return false;\">ReRx</a>");
            }

            String url = item.getURL();
            if (item.isURLJavaScript()) {
                divReloadInfo = trackWindowString(url, divReloadUrl, cmd, pattern);
                out.println(
                    "<a class='links' style='" + colour
                    + "' onmouseover=\"this.className='linkhover'\"onmouseout=\"this.className='links'\" href='#' onclick=\""
                    + divReloadInfo + url + "\" title='" + Encode.forHtmlAttribute(item.getLinkTitle()) + "'>");
            } else {
                out.println(
                    "<a class='links' style='" + colour
                    + "' onmouseover=\"this.className='linkhover'\" onmouseout=\"this.className='links'\" href=\"" + url
                    + "\" title='" + Encode.forHtmlAttribute(item.getLinkTitle()) + "' target=\"_blank\">");
            }

            out.println(item.getTitle());
            out.println("</a>");
            out.println("</span>");

            if (item.getDate() != null) {
                out.println(
                    "<span style=\"z-index: 100; " + dateColour
                    + " overflow:hidden; position:relative; height:1.2em; white-space:nowrap; float:right; text-align:right;\">");

                if (item.isURLJavaScript()) {
                    divReloadInfo = trackWindowString(url, divReloadUrl, cmd, pattern);
                    out.println(
                        "...<a class='links' style='margin-right: 2px;" + colour
                        + "' onmouseover=\"this.className='linkhover'\" onmouseout=\"this.className='links'\" href='#' onclick=\""
                        + divReloadInfo + url + "\" title='" + Encode.forHtmlAttribute(item.getLinkTitle()) + "'>");
                } else {
                    out.println(
                        "...<a class='links' style='margin-right: 2px;" + colour
                        + "' onmouseover=\"this.className='linkhover'\" onmouseout=\"this.className='links'\" href=\"" + url
                        + "\" title='" + Encode.forHtmlAttribute(item.getLinkTitle()) + "' target=\"_blank\">");
                }

                if (item.getValue() != null && !item.getValue().trim().equals("")) {
                    out.println(item.getValue());
                }
                out.println(DateUtils.getDate(item.getDate(), dateFormat, request.getLocale()));
                out.println("</a>");
                out.println("</span>");
            }
            out.println("</li>");
        }

        return j;
    }

    public String trackWindowString(String url, String reloadUrl, String cmd, Pattern pattern) {
		String windowName, divReloadInfo = "";
		if( url.startsWith("popupPage") ) {
	    	Matcher matcher = pattern.matcher(url);
	    	if( matcher.find() ) {
	    		windowName = matcher.group(1);
	    		reloadUrl += "&numToDisplay=6&cmd=" + cmd;
	    		divReloadInfo = "reloadWindows['" + windowName + "'] = '" + reloadUrl + "';reloadWindows['"+ windowName + "div'] = '" + cmd + "';";
	    	}

		}

		return divReloadInfo;
    }

    
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1780193738074L));
    _jspx_dependants.put("jar:file:/home/dmoniz/projects/oscar/catalina_base/webapps/oscar/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("/WEB-INF/security.tld", Long.valueOf(1780193738112L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("oscar.util");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(22);
    _jspx_imports_classes.add("org.apache.commons.lang.StringUtils");
    _jspx_imports_classes.add("org.oscarehr.util.SpringUtils");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.io.IOException");
    _jspx_imports_classes.add("org.oscarehr.common.dao.SystemPreferencesDao");
    _jspx_imports_classes.add("oscar.oscarEncounter.pageUtil.NavBarDisplayDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.quatro.model.security.Secobjprivilege");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.regex.Matcher");
    _jspx_imports_classes.add("org.oscarehr.common.model.SystemPreferences");
    _jspx_imports_classes.add("org.owasp.encoder.Encode");
    _jspx_imports_classes.add("com.quatro.dao.security.SecobjprivilegeDao");
    _jspx_imports_classes.add("java.util.regex.Pattern");
    _jspx_imports_classes.add("org.apache.commons.lang.StringEscapeUtils");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

      String roleName$ = (String)session.getAttribute("userrole") + "," + (String) session.getAttribute("user");
      boolean authed=true;

      out.write('\n');
      //  security:oscarSec
      oscar.login.tld.SecurityTag _jspx_th_security_005foscarSec_005f0 = (oscar.login.tld.SecurityTag) _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.get(oscar.login.tld.SecurityTag.class);
      _jspx_th_security_005foscarSec_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005foscarSec_005f0.setParent(null);
      // /oscarEncounter/LeftNavBarDisplay.jsp(32,0) name = roleName type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setRoleName(roleName$);
      // /oscarEncounter/LeftNavBarDisplay.jsp(32,0) name = objectName type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setObjectName("_eChart");
      // /oscarEncounter/LeftNavBarDisplay.jsp(32,0) name = rights type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setRights("r");
      // /oscarEncounter/LeftNavBarDisplay.jsp(32,0) name = reverse type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setReverse(true);
      int _jspx_eval_security_005foscarSec_005f0 = _jspx_th_security_005foscarSec_005f0.doStartTag();
      if (_jspx_eval_security_005foscarSec_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write('\n');
        out.write('	');
authed=false; 
        out.write('\n');
        out.write('	');
response.sendRedirect("../securityError.jsp?type=_eChart");
        out.write('\n');
      }
      if (_jspx_th_security_005foscarSec_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.reuse(_jspx_th_security_005foscarSec_005f0);
      out.write('\n');

if(!authed) {
	return;
}

      out.write("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');

        long startTime = System.currentTimeMillis();
        NavBarDisplayDAO dao = (NavBarDisplayDAO)request.getAttribute("DAO");
        String js = dao.getJavaScript();
        int maxColumnHeight = 40;  //break into columns after maxColumnHeight items reached
        int menuWidth = 125;


        //Is there java script to insert in page?  Then do it
        if( js != null ) {
        
      out.write('\n');
      out.print(js);
      out.write('\n');
 } 
      out.write("\n<input type=hidden name=\"reloadUrl\" value=\"");
      out.print(dao.getReloadUrl());
      out.write("\"/>\n");

        //Do we have a '+' command to display on the right of the module header?
        String rh = dao.getRightHeadingID();
		String rhid = dao.getRightHeadingID();
		com.quatro.service.security.SecurityManager securityMgr = new com.quatro.service.security.SecurityManager();

		if( !rh.equals("") && securityMgr.hasWriteAccess("_" + ((String)request.getAttribute("cmd")).toLowerCase(),roleName$)) {
        
      out.write("\n<div id='menuTitle");
      out.print(rh);
      out.write("'\n	style=\"width: 10%; float: right; text-align: center;\">\n<h3 style=\"padding:0px; ");
      out.print(getBackgroundColor(dao));
      out.write("\"><a href=\"javascript:void(0);\"\n	");
      out.print(dao.numPopUpMenuItems() > 0 ? "onmouseover" : "onclick");
      out.write('=');
      out.write('"');
      out.print(dao.getRightURL());
      out.write("\">+</a></h3>\n</div>\n");

        int num;
        //if there is a pop up menu then grab all of the items and format according to number
        if( (num = dao.numPopUpMenuItems()) > 0 ) {
        boolean columns = false;
        String style;
        String width;
        if( num > maxColumnHeight) {
        columns = true;
        menuWidth *= 2;
        }
        
      out.write("\n<div id='menu");
      out.print(rh);
      out.write("' class='menu' style='width: ");
      out.print(menuWidth);
      out.write(";px'\n	onclick='event.cancelBubble = true;'>\n<h3 style='text-align: center'>");
      out.print(dao.getMenuHeader());
      out.write("</h3>\n");

            for(int idx = 0; idx < num; ++idx) {
            if( columns )
            style = idx % 2 == 0 ? "menuItemleft" : "menuItemright";
            else
            style = "menuItemleft";
            
      out.write(" <a href=\"#\" class=\"");
      out.print(style);
      out.write("\"\n	onmouseover='this.style.color=\"black\"'\n	onmouseout='this.style.color=\"white\"'\n	onclick=\"");
      out.print(dao.getPopUpUrl(idx));
      out.write("; return false;\">");
      out.print(dao.getPopUpText(idx));
      out.write("</a>\n");

            if( columns && idx % 2 == 1) {
            
      out.write(" <br>\n");

            }
            else if( !columns ){
            
      out.write(" <br>\n");

            }
            } //end for
            
      out.write("\n</div>\n");

        } //end if menu items

        } //end if there is a right hand header
        else {
        	if(!rh.equals("")) {
        	 
      out.write("\n             <div id='menuTitle");
      out.print(rh);
      out.write("' style=\"width: 10%; float: right; text-align: center;\">\n      			<h3 style=\"padding:0px; ");
      out.print(getBackgroundColor(dao));
      out.write("\">&nbsp;</h3>\n      	   </div>\n             ");

        } }

        //left hand module header comes last as it's displayed as a block
        
      out.write("\n<div style=\"clear: left; float: left; width: 90%;\">\n<h3 style=\"width:100%; ");
      out.print(getBackgroundColor(dao));
      out.write("\"><a href=\"#\"\n	onclick=\"");
      out.print(dao.getLeftURL());
      out.write("; return false;\">");
      out.print(dao.getLeftHeading());
      out.write("</a></h3>\n</div>\n\n<ul id=\"");
      out.print(request.getAttribute("navbarName"));
      out.write("list\">\n	");

            //now we display the actual items of the module
            String manageItems = "";
            String div = (String)request.getAttribute("navbarName");
            div = div.trim();
            int numItems = dao.numItems();
            StringBuilder reloadURL = new StringBuilder(request.getParameter("reloadURL") + "&reloadURL=" + request.getParameter("reloadURL"));
            String strToDisplay = request.getParameter("numToDisplay");
            int numToDisplay;
            boolean xpanded = false;
            int displayThreshold = 6;

            if( strToDisplay != null ) {
                numToDisplay = Integer.parseInt(strToDisplay);
				reloadURL.append("&numToDisplay=" + strToDisplay);
                if( numItems > numToDisplay ) {
                    String xpandUrl = request.getParameter("reloadURL") + "&reloadURL=" + request.getParameter("reloadURL") + "&cmd=" + div;
                    manageItems = xpandUrl;
                }
            }
            else {
                numToDisplay = numItems;
                if( numToDisplay > displayThreshold ) {
                    xpanded = true;
                }
            }
			reloadURL.append("&cmd=" + div);
            int numDisplayed = 0;

            ArrayList<NavBarDisplayDAO.Item> current = new ArrayList<NavBarDisplayDAO.Item>();
            ArrayList<NavBarDisplayDAO.Item> pastDates = new ArrayList<NavBarDisplayDAO.Item>();
            ArrayList<NavBarDisplayDAO.Item> noDates = new ArrayList<NavBarDisplayDAO.Item>();
            ArrayList<NavBarDisplayDAO.Item> duePreventions = new ArrayList<NavBarDisplayDAO.Item>();
            Calendar threshold = Calendar.getInstance();
            threshold.add(Calendar.MONTH, -3);
            Date threeMths = threshold.getTime();
            int j;
            SystemPreferencesDao systemPreferencesDao = SpringUtils.getBean(SystemPreferencesDao.class);
            SystemPreferences preference =
                systemPreferencesDao.findPreferenceByName("echart_show_group_document_by_type");
            boolean groupByType = preference != null && Boolean.parseBoolean(preference.getValue());

            if (groupByType && request.getAttribute("navbarName").equals("docs") && !xpanded) {
                  dao.sortItems(NavBarDisplayDAO.DATESORT_ASC);
            }

            for(j=0; j<numItems; j++) {
                NavBarDisplayDAO.Item item = dao.getItem(j);
                Date d = item.getDate();
                String itemColour = item.getColour();

                if (div.equals("tickler") || div.equals("labs"))
                {
                    if( d == null )
                    {
                        noDates.add(item);
                    }
                    else
                    {
                        current.add(item);
                    }
                }
                else
                {
                  if (groupByType && request.getAttribute("navbarName").equals("docs")) {
                    if( xpanded) {
                        // show folder headings when xpanded
                        current.add(item);
                    } else {
                        if( d != null ) {
                            // hide folder headings when list is compact
                            current.add(item);
                        }
                    }
                  } else {
                    if( d == null )
                        noDates.add(item);
                    else if( d.compareTo(threeMths) < 0)
                        if(itemColour.equals("#FF0000") && div.equals("preventions"))
                            duePreventions.add(item);
                        else
                            pastDates.add(item);
                    else
                        current.add(item);
                  }
               }
            }

            StringBuilder jscode = new StringBuilder();

            if(div.equals("preventions")){
                numDisplayed = display(duePreventions, numToDisplay, numDisplayed, manageItems, xpanded, numItems, jscode, displayThreshold, reloadURL.toString(),dao.getDivId(),request,out);
                numDisplayed += display(noDates, numToDisplay, numDisplayed, manageItems, xpanded, numItems, jscode, displayThreshold, reloadURL.toString(), dao.getDivId(), request, out);
            }
            else if(div.equals("Rx")) {
                numDisplayed = displayRXList(noDates, numToDisplay, numDisplayed, manageItems, xpanded, numItems, jscode, displayThreshold, reloadURL.toString(), dao.getDivId(), request, out);
            }
else{
                numDisplayed = display(noDates, numToDisplay, numDisplayed, manageItems, xpanded, numItems, jscode, displayThreshold, reloadURL.toString(), dao.getDivId(), request, out);
            }

            if( numDisplayed < numToDisplay ){
               numDisplayed += display(current, numToDisplay, numDisplayed, manageItems, xpanded, numItems, jscode, displayThreshold, reloadURL.toString(), dao.getDivId(), request, out);
            }

            if( numDisplayed < numToDisplay ){
                numDisplayed += display(pastDates, numToDisplay, numDisplayed, manageItems, xpanded, numItems, jscode, displayThreshold, reloadURL.toString(), dao.getDivId(),request, out);
            }

            if( numDisplayed == 0 ) {
                out.println("<li>&nbsp;</li>");
            }
            
      out.write("\n</ul>\n<input type=\"hidden\" id=\"");
      out.print(request.getAttribute("navbarName"));
      out.write("num\"\n	value=\"");
      out.print(numDisplayed);
      out.write("\" />\n");

        out.println("<script type=\"text/javascript\">" + jscode.toString() + "</script>");
    
      out.write('\n');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /oscarEncounter/LeftNavBarDisplay.jsp(59,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /oscarEncounter/LeftNavBarDisplay.jsp(59,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/oscarEncounter/LeftNavBarDisplay.jsp(59,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /oscarEncounter/LeftNavBarDisplay.jsp(59,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setScope("request");
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }
}
