/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2026-06-03 23:02:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.oscarRx;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.oscarehr.common.model.PartialDate;
import org.apache.commons.lang.StringEscapeUtils;
import org.oscarehr.casemgmt.web.PrescriptDrug;
import oscar.oscarRx.data.*;
import oscar.oscarProvider.data.ProviderMyOscarIdData;
import oscar.oscarDemographic.data.DemographicData;
import oscar.OscarProperties;
import oscar.log.*;
import org.oscarehr.casemgmt.service.CaseManagementManager;
import org.springframework.web.context.WebApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;
import org.oscarehr.casemgmt.model.CaseManagementNoteLink;
import org.oscarehr.casemgmt.model.CaseManagementNote;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Enumeration;
import org.oscarehr.util.SpringUtils;
import org.oscarehr.util.SessionConstants;
import java.util.List;
import oscar.util.StringUtils;
import org.oscarehr.PMmodule.caisi_integrator.CaisiIntegratorManager;
import org.oscarehr.util.LoggedInInfo;
import org.oscarehr.common.dao.DrugReasonDao;
import org.oscarehr.common.model.DrugReason;
import java.util.ArrayList;
import oscar.util.*;
import java.util.*;
import org.oscarehr.common.model.Drug;
import org.oscarehr.common.dao.*;
import org.oscarehr.managers.DrugDispensingManager;
import org.oscarehr.managers.CodingSystemManager;

public final class ListDrugs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {



String getName(Drug prescriptDrug){
    String searchString = prescriptDrug.getBrandName();
    if (searchString == null) {
        searchString = prescriptDrug.getCustomName();
    }
    if (searchString == null) {
        searchString = prescriptDrug.getRegionalIdentifier();
    }
    if (searchString == null) {
        searchString = prescriptDrug.getSpecial();
    }
    return searchString;
}

    String getClassColour(Drug drug, long referenceTime, long durationToSoon){
        StringBuilder sb = new StringBuilder("class=\"");

        if (!drug.isLongTerm() && (drug.isCurrent() && drug.getEndDate() != null && (drug.getEndDate().getTime() - referenceTime <= durationToSoon))) {
            sb.append("expireInReference ");
        }

        if ((drug.isCurrent() && !drug.isArchived()) || drug.isLongTerm()) {
            sb.append("currentDrug ");
        }

        if (drug.isArchived()) {
            sb.append("archivedDrug ");
        }

        if(!drug.isLongTerm() && !drug.isCurrent()) {
            sb.append("expiredDrug ");
        }

        if(drug.isLongTerm()){
            sb.append("longTermMed ");
        }

        if(drug.isDiscontinued()){
            sb.append("discontinued ");
        }

        if(drug.isDeleted()){
                sb.append("deleted ");

        }

        if(drug.getOutsideProviderName() !=null && !drug.getOutsideProviderName().equals("")  ) {
        	sb = new StringBuilder("class=\"");
        	sb.append("external ");
        }
        if (drug.getRemoteFacilityName() != null){
        	sb = new StringBuilder("class=\"");
        	sb.append("external ");
        }
        String retval = sb.toString();

        if(retval.equals("class=\"")){
            return "";
        }

        return retval.substring(0,retval.length())+"\"";

    }




String displayDrugReason(CodingSystemManager codingSystemManager, List<DrugReason> drugReasons,boolean title){
	StringBuilder sb = new StringBuilder();
	boolean multiLoop = false;

	for(DrugReason drugReason:drugReasons){
		if(multiLoop){
			sb.append(", ");
		}
		String codeDescr = codingSystemManager.getCodeDescription( drugReason.getCodingSystem(), drugReason.getCode() );
		if(codeDescr != null) {
			sb.append(StringEscapeUtils.escapeHtml(codeDescr));
		} else {
			sb.append( drugReason.getCode() );
		}
		multiLoop = true;
	}
	if(sb.toString().equals("")){
		if(title) {
			return "No diseases are associated with this medication";
		}
		return "+";
	}

	return sb.toString();
}


  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/struts-logic.tld", Long.valueOf(1780193738112L));
    _jspx_dependants.put("/WEB-INF/indivo-tag.tld", Long.valueOf(1780193737919L));
    _jspx_dependants.put("/WEB-INF/struts-html.tld", Long.valueOf(1780193738112L));
    _jspx_dependants.put("/WEB-INF/oscar-tag.tld", Long.valueOf(1780193738112L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1780193738074L));
    _jspx_dependants.put("/WEB-INF/struts-bean.tld", Long.valueOf(1780193738112L));
    _jspx_dependants.put("jar:file:/home/dmoniz/projects/oscar/catalina_base/webapps/oscar/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("/WEB-INF/security.tld", Long.valueOf(1780193738112L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(11);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("oscar.oscarRx.data");
    _jspx_imports_packages.add("oscar.log");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("org.oscarehr.common.dao");
    _jspx_imports_packages.add("oscar.util");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(35);
    _jspx_imports_classes.add("org.oscarehr.common.model.Drug");
    _jspx_imports_classes.add("java.util.Enumeration");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("org.oscarehr.PMmodule.caisi_integrator.CaisiIntegratorManager");
    _jspx_imports_classes.add("org.oscarehr.managers.CodingSystemManager");
    _jspx_imports_classes.add("org.oscarehr.util.SessionConstants");
    _jspx_imports_classes.add("org.oscarehr.util.SpringUtils");
    _jspx_imports_classes.add("org.springframework.web.context.support.WebApplicationContextUtils");
    _jspx_imports_classes.add("org.springframework.web.context.WebApplicationContext");
    _jspx_imports_classes.add("org.oscarehr.casemgmt.model.CaseManagementNoteLink");
    _jspx_imports_classes.add("org.oscarehr.casemgmt.model.CaseManagementNote");
    _jspx_imports_classes.add("org.oscarehr.common.dao.DrugReasonDao");
    _jspx_imports_classes.add("org.oscarehr.casemgmt.service.CaseManagementManager");
    _jspx_imports_classes.add("org.oscarehr.common.model.PartialDate");
    _jspx_imports_classes.add("oscar.oscarDemographic.data.DemographicData");
    _jspx_imports_classes.add("oscar.OscarProperties");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.oscarehr.casemgmt.web.PrescriptDrug");
    _jspx_imports_classes.add("org.oscarehr.common.model.DrugReason");
    _jspx_imports_classes.add("oscar.util.StringUtils");
    _jspx_imports_classes.add("org.oscarehr.util.LoggedInInfo");
    _jspx_imports_classes.add("org.apache.commons.lang.StringEscapeUtils");
    _jspx_imports_classes.add("oscar.oscarProvider.data.ProviderMyOscarIdData");
    _jspx_imports_classes.add("org.oscarehr.managers.DrugDispensingManager");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fname_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fnotPresent_0026_005fscope_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fpresent_0026_005fscope_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fname_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fnotPresent_0026_005fscope_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fpresent_0026_005fscope_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fname_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fnotPresent_0026_005fscope_005fname.release();
    _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fpresent_0026_005fscope_005fname.release();
    _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.release();
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
      //  bean:define
      org.apache.struts.taglib.bean.DefineTag _jspx_th_bean_005fdefine_005f0 = (org.apache.struts.taglib.bean.DefineTag) _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fname_005fid_005fnobody.get(org.apache.struts.taglib.bean.DefineTag.class);
      _jspx_th_bean_005fdefine_005f0.setPageContext(_jspx_page_context);
      _jspx_th_bean_005fdefine_005f0.setParent(null);
      // /oscarRx/ListDrugs.jsp(51,0) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fdefine_005f0.setId("patient");
      // /oscarRx/ListDrugs.jsp(51,0) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fdefine_005f0.setType("oscar.oscarRx.data.RxPatientData.Patient");
      // /oscarRx/ListDrugs.jsp(51,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_bean_005fdefine_005f0.setName("Patient");
      int _jspx_eval_bean_005fdefine_005f0 = _jspx_th_bean_005fdefine_005f0.doStartTag();
      if (_jspx_th_bean_005fdefine_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fname_005fid_005fnobody.reuse(_jspx_th_bean_005fdefine_005f0);
      oscar.oscarRx.data.RxPatientData.Patient patient = null;
      patient = (oscar.oscarRx.data.RxPatientData.Patient) _jspx_page_context.findAttribute("patient");
      out.write('\n');
      if (_jspx_meth_logic_005fnotPresent_005f0(_jspx_page_context))
        return;
      out.write('\n');
      //  logic:present
      org.apache.struts.taglib.logic.PresentTag _jspx_th_logic_005fpresent_005f0 = (org.apache.struts.taglib.logic.PresentTag) _005fjspx_005ftagPool_005flogic_005fpresent_0026_005fscope_005fname.get(org.apache.struts.taglib.logic.PresentTag.class);
      _jspx_th_logic_005fpresent_005f0.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fpresent_005f0.setParent(null);
      // /oscarRx/ListDrugs.jsp(55,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fpresent_005f0.setName("RxSessionBean");
      // /oscarRx/ListDrugs.jsp(55,0) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fpresent_005f0.setScope("session");
      int _jspx_eval_logic_005fpresent_005f0 = _jspx_th_logic_005fpresent_005f0.doStartTag();
      if (_jspx_eval_logic_005fpresent_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n    ");
          //  bean:define
          org.apache.struts.taglib.bean.DefineTag _jspx_th_bean_005fdefine_005f1 = (org.apache.struts.taglib.bean.DefineTag) _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody.get(org.apache.struts.taglib.bean.DefineTag.class);
          _jspx_th_bean_005fdefine_005f1.setPageContext(_jspx_page_context);
          _jspx_th_bean_005fdefine_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fpresent_005f0);
          // /oscarRx/ListDrugs.jsp(56,4) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_bean_005fdefine_005f1.setId("bean");
          // /oscarRx/ListDrugs.jsp(56,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_bean_005fdefine_005f1.setType("oscar.oscarRx.pageUtil.RxSessionBean");
          // /oscarRx/ListDrugs.jsp(56,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_bean_005fdefine_005f1.setName("RxSessionBean");
          // /oscarRx/ListDrugs.jsp(56,4) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_bean_005fdefine_005f1.setScope("session");
          int _jspx_eval_bean_005fdefine_005f1 = _jspx_th_bean_005fdefine_005f1.doStartTag();
          if (_jspx_th_bean_005fdefine_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
          _005fjspx_005ftagPool_005fbean_005fdefine_0026_005ftype_005fscope_005fname_005fid_005fnobody.reuse(_jspx_th_bean_005fdefine_005f1);
          oscar.oscarRx.pageUtil.RxSessionBean bean = null;
          bean = (oscar.oscarRx.pageUtil.RxSessionBean) _jspx_page_context.findAttribute("bean");
          out.write("\n    ");
          if (_jspx_meth_logic_005fequal_005f0(_jspx_th_logic_005fpresent_005f0, _jspx_page_context))
            return;
          out.write('\n');
          int evalDoAfterBody = _jspx_th_logic_005fpresent_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fpresent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005flogic_005fpresent_0026_005fscope_005fname.reuse(_jspx_th_logic_005fpresent_005f0);
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');

    String roleName$ = (String)session.getAttribute("userrole") + "," + (String) session.getAttribute("user");
    boolean authed=true;

      out.write('\n');
      //  security:oscarSec
      oscar.login.tld.SecurityTag _jspx_th_security_005foscarSec_005f0 = (oscar.login.tld.SecurityTag) _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.get(oscar.login.tld.SecurityTag.class);
      _jspx_th_security_005foscarSec_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005foscarSec_005f0.setParent(null);
      // /oscarRx/ListDrugs.jsp(68,0) name = roleName type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setRoleName(roleName$);
      // /oscarRx/ListDrugs.jsp(68,0) name = objectName type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setObjectName("_rx");
      // /oscarRx/ListDrugs.jsp(68,0) name = rights type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setRights("r");
      // /oscarRx/ListDrugs.jsp(68,0) name = reverse type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setReverse(true);
      int _jspx_eval_security_005foscarSec_005f0 = _jspx_th_security_005foscarSec_005f0.doStartTag();
      if (_jspx_eval_security_005foscarSec_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write('\n');
        out.write('	');
authed=false; 
        out.write('\n');
        out.write('	');
response.sendRedirect("../securityError.jsp?type=_rx");
        out.write('\n');
      }
      if (_jspx_th_security_005foscarSec_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.reuse(_jspx_th_security_005foscarSec_005f0);
      out.write('\n');

	if(!authed) {
		return;
	}

      out.write('\n');
      out.write('\n');

	LoggedInInfo loggedInInfo=LoggedInInfo.getLoggedInInfoFromSession(request);
	com.quatro.service.security.SecurityManager securityManager = new com.quatro.service.security.SecurityManager();
	oscar.oscarRx.pageUtil.RxSessionBean bean = (oscar.oscarRx.pageUtil.RxSessionBean) pageContext.findAttribute("bean");
	PartialDateDao partialDateDao = SpringUtils.getBean(PartialDateDao.class);

	boolean showall = false;
	if (request.getParameter("show") != null) {
	    if (request.getParameter("show").equals("all")) {
	        showall = true;
	    }
	}

	CodingSystemManager codingSystemManager = SpringUtils.getBean(CodingSystemManager.class);

	boolean integratorEnabled = loggedInInfo.getCurrentFacility().isIntegratorEnabled();
	String annotation_display = org.oscarehr.casemgmt.model.CaseManagementNoteLink.DISP_PRESCRIP;
	String heading = request.getParameter("heading");

if (heading != null){

      out.write("\n<h4 style=\"margin-bottom:1px;margin-top:3px;\">");
      out.print(heading);
      out.write("</h4>\n");
}
      out.write("\n<div class=\"drugProfileText\" style=\"\">\n    <table width=\"100%\" cellpadding=\"3\" border=\"0\" class=\"sortable\" id=\"Drug_table");
      out.print(heading);
      out.write("\">\n        <tr>\n        	<th align=\"left\"><b>Entered Date</b></th>\n            <th align=\"left\"><b>");
      if (_jspx_meth_bean_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</b></th>\n            <th align=\"left\"><b>Days to Exp</b></th>\n            <th align=\"left\"><b>LT Med</b></th>\n            <th align=\"left\"><b>");
      if (_jspx_meth_bean_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("</b></th>\n			");
if(securityManager.hasWriteAccess("_rx",roleName$,true)) {
      out.write("\n            <th align=\"center\" width=\"35px\"><b>");
      if (_jspx_meth_bean_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("</b></th>\n            	");
if(!OscarProperties.getInstance().getProperty("rx.delete_drug.hide","false").equals("true")) {
      out.write("\n            	<th align=\"center\" width=\"35px\"><b>");
      if (_jspx_meth_bean_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("</b></th>\n            ");
 	}
			}
            
      out.write("\n            <th align=\"center\" width=\"35px\"><b>");
      if (_jspx_meth_bean_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("</b></th>\n			<th align=\"center\" width=\"35px\" title=\"");
      if (_jspx_meth_bean_005fmessage_005f5(_jspx_page_context))
        return;
      out.write("\"><b>");
      if (_jspx_meth_bean_005fmessage_005f6(_jspx_page_context))
        return;
      out.write("</b></th>\n            <th align=\"center\" width=\"35px\"><b>");
      if (_jspx_meth_bean_005fmessage_005f7(_jspx_page_context))
        return;
      out.write("</b></th>\n            ");
if(securityManager.hasWriteAccess("_rx",roleName$,true)) {
      out.write("\n            	<th align=\"center\" width=\"15px\">&nbsp;</th>\n            ");
 } 
      out.write("\n            <th align=\"center\">");
      if (_jspx_meth_bean_005fmessage_005f8(_jspx_page_context))
        return;
      out.write("</th>\n            <th align=\"center\" title=\"");
      if (_jspx_meth_bean_005fmessage_005f9(_jspx_page_context))
        return;
      out.write('"');
      out.write('>');
      if (_jspx_meth_bean_005fmessage_005f10(_jspx_page_context))
        return;
      out.write("</th>\n            ");
if(OscarProperties.getInstance().getProperty("rx.enable_internal_dispensing","false").equals("true")) {
      out.write("\n             <th align=\"center\">");
      if (_jspx_meth_bean_005fmessage_005f11(_jspx_page_context))
        return;
      out.write("</th>\n             ");
} 
      out.write("\n             <th align=\"center\"></th>\n        </tr>\n\n        ");

	        List<Drug> prescriptDrugs = null;
            CaseManagementManager caseManagementManager = (CaseManagementManager) SpringUtils.getBean("caseManagementManager");

            if(showall) {
            	prescriptDrugs = caseManagementManager.getPrescriptions(loggedInInfo, patient.getDemographicNo(), showall);
            	//Collections.sort(prescriptDrugs,new oscar.oscarRx.util.ShowAllSorter());
            }
            else {
                prescriptDrugs = caseManagementManager.getCurrentPrescriptions(patient.getDemographicNo());
            }

            DrugReasonDao drugReasonDao  = (DrugReasonDao) SpringUtils.getBean("drugReasonDao");

            DrugDispensingManager drugDispensingManager = SpringUtils.getBean(DrugDispensingManager.class);
            List<String> reRxDrugList=bean.getReRxDrugIdList();
            Collections.sort(prescriptDrugs, Drug.START_DATE_COMPARATOR);

            long now = System.currentTimeMillis();
            long month = 1000L * 60L * 60L * 24L * 30L;
			for (int x=0;x<prescriptDrugs.size();x++) {
				Drug prescriptDrug = prescriptDrugs.get(x);
				boolean isPrevAnnotation=false;
                String styleColor = "";
                //test for previous note
                HttpSession se = request.getSession();
                Integer tableName = caseManagementManager.getTableNameByDisplay(annotation_display);

                CaseManagementNoteLink cml = null;
                CaseManagementNote p_cmn = null;

                if (prescriptDrug.getRemoteFacilityId()!=null)
                {
                	cml = caseManagementManager.getLatestLinkByTableId(tableName, Long.parseLong(prescriptDrug.getId().toString()));
                }

                if (cml!=null) {p_cmn = caseManagementManager.getNote(cml.getNoteId().toString());}
                if (p_cmn!=null){isPrevAnnotation=true;}

                if (request.getParameter("status") != null) { //TODO: Redo this in a better way
                    String stat = request.getParameter("status");
                    if (stat.equals("active") && !prescriptDrug.isLongTerm() && !prescriptDrug.isCurrent()) {
                        continue;
                    } else if (stat.equals("inactive") && prescriptDrug.isCurrent()) {
                        continue;
                    }
                }
                if (request.getParameter("longTermOnly") != null && request.getParameter("longTermOnly").equals("true")){
                    if (!prescriptDrug.isLongTerm()){
                      continue;
                    }
                }
                if (request.getParameter("longTermOnly") != null && request.getParameter("longTermOnly").equals("acute")){
                    if (prescriptDrug.isLongTerm()){
                      continue;
                    }
                }
                if(request.getParameter("drugLocation")!=null&&request.getParameter("drugLocation").equals("external")){
                    if(!prescriptDrug.isExternal())
                        continue;
                }

                //add all long term med drugIds to an array.
                styleColor = getClassColour( prescriptDrug, now, month);
                String specialText=prescriptDrug.getSpecial();
                specialText= specialText == null ? "" : specialText.replace("\n"," ");
                Integer prescriptIdInt=prescriptDrug.getId();
                String bn=prescriptDrug.getBrandName();

                boolean startDateUnknown = prescriptDrug.getStartDateUnknown();
        
      out.write("\n        <tr>\n        <td valign=\"top\">");
      out.print(oscar.util.UtilDateUtilities.DateToString(prescriptDrug.getCreateDate()));
      out.write("</a></td>\n            <td valign=\"top\">\n            	");
 if(startDateUnknown) { 
      out.write("\n\n            	");
 } else {
            		String startDate = oscar.util.UtilDateUtilities.DateToString(prescriptDrug.getRxDate());
            		startDate = partialDateDao.getDatePartial(startDate, PartialDate.DRUGS,  prescriptDrug.getId(), PartialDate.DRUGS_STARTDATE);
            	
      out.write("\n		    ");
      out.print(startDate);
      out.write("</nobr>\n            	");
 } 
      out.write("\n            </td>\n            <td valign=\"top\">\n            	");
 if(startDateUnknown) { 
      out.write("\n\n            	");
 } else { 
      out.write("\n            		");
      out.print(prescriptDrug.daysToExpire());
      out.write("\n            	");
 } 
      out.write("\n            </td>\n            <td valign=\"top\">\n                ");

                        if(prescriptDrug.isLongTerm())
                        {
                        
      out.write("\n                                <a id=\"longTermDrug_");
      out.print(prescriptIdInt);
      out.write("\" title=\"");
      if (_jspx_meth_bean_005fmessage_005f12(_jspx_page_context))
        return;
      out.write("\" onclick=\"changeLt('");
      out.print(prescriptIdInt);
      out.write("', true);\" href=\"javascript:void(0);\">\n                                        ");
      if (_jspx_meth_bean_005fmessage_005f13(_jspx_page_context))
        return;
      out.write("\n                                </a>\n                        ");

                        }
                        else
                        {
                                if (prescriptDrug.getRemoteFacilityId()==null)
                                {
                                        
      out.write("\n                                                        ");

                                                                if(securityManager.hasWriteAccess("_rx",roleName$,true)) {
                                                        
      out.write("\n                                                <a id=\"notLongTermDrug_");
      out.print(prescriptIdInt);
      out.write("\" title=\"");
      if (_jspx_meth_bean_005fmessage_005f14(_jspx_page_context))
        return;
      out.write("\" onclick=\"changeLt('");
      out.print(prescriptIdInt);
      out.write("', false);\" href=\"javascript:void(0);\">\n                                                ");
      if (_jspx_meth_bean_005fmessage_005f15(_jspx_page_context))
        return;
      out.write("\n                                                </a>\n                                                        ");
 } else { 
      out.write("\n                                                <span style=\"color:blue\">no</span>\n                                        ");
 } 
      out.write("\n\n                                        ");

                                }
                                else
                                {
                                        
      out.write("\n                                        L\n                                        ");

                                }
                                }
                                
      out.write("\n            </td>\n\n			");

			//display comment as tooltip if not null - simply using the TITLE attr
			String xComment=prescriptDrug.getComment();
			String tComment="";
			if(xComment!=null ){
				tComment="TITLE='"+xComment+" '";
			}

			
      out.write("\n            <td valign=\"top\"><a id=\"prescrip_");
      out.print(prescriptIdInt);
      out.write('"');
      out.write(' ');
      out.print(styleColor);
      out.write(" href=\"StaticScript2.jsp?regionalIdentifier=");
      out.print(prescriptDrug.getRegionalIdentifier());
      out.write("&amp;cn=");
      out.print(response.encodeURL(prescriptDrug.getCustomName()));
      out.write("&amp;bn=");
      out.print(response.encodeURL(bn));
      out.write("&amp;atc=");
      out.print(prescriptDrug.getAtc());
      out.write("\"   ");
      out.print(tComment);
      out.write("  title=\"");
      out.print(prescriptDrug.getGenericName());
      out.write('"');
      out.write(' ');
      out.write('>');
      out.print(RxPrescriptionData.getFullOutLine(prescriptDrug.getSpecial()).replaceAll(";", " "));
      out.write("</a></td>\n			");

	           	if(securityManager.hasWriteAccess("_rx",roleName$,true)) {
           	
      out.write("\n            <td width=\"20px\" align=\"center\" valign=\"top\">\n                ");
if (prescriptDrug.getRemoteFacilityName() == null) {
      out.write("\n                <input id=\"reRxCheckBox_");
      out.print(prescriptIdInt);
      out.write("\" type=CHECKBOX onclick=\"updateReRxDrugId(this.id)\" ");
if(reRxDrugList.contains(prescriptIdInt.toString())){
      out.write("checked");
}
      out.write(" name=\"checkBox_");
      out.print(prescriptIdInt);
      out.write("\">\n                <a name=\"rePrescribe\" style=\"vertical-align:top\" id=\"reRx_");
      out.print(prescriptIdInt);
      out.write('"');
      out.write(' ');
      out.print(styleColor);
      out.write(" href=\"javascript:void(0)\" onclick=\"represcribe(this, ");
      out.print(prescriptIdInt);
      out.write(")\">ReRx</a>\n                ");
} else {
      out.write("\n                <form action=\"");
      out.print(request.getContextPath());
      out.write("/oscarRx/searchDrug.do\" method=\"post\">\n                    <input type=\"hidden\" name=\"demographicNo\" value=\"");
      out.print(patient.getDemographicNo());
      out.write("\" />\n                    <input type=\"hidden\" name=\"searchString\" value=\"");
      out.print(getName(prescriptDrug));
      out.write("\" />\n                    <input type=\"submit\" class=\"ControlPushButton\" value=\"Search to Re-prescribe\" />\n                </form>\n                ");
}
      out.write("\n            </td>\n			");
if(!OscarProperties.getInstance().getProperty("rx.delete_drug.hide","false").equals("true")) { 
      out.write("\n            <td width=\"20px\" align=\"center\" valign=\"top\">\n                ");
if (prescriptDrug.getRemoteFacilityName() == null) {
      out.write("\n                   <a id=\"del_");
      out.print(prescriptIdInt);
      out.write("\" name=\"delete\" ");
      out.print(styleColor);
      out.write(" href=\"javascript:void(0);\" onclick=\"Delete2(this);\">Del</a>\n                ");
}
      out.write("\n            </td>\n\n			");
 }
	         }
			
      out.write("\n            <td width=\"20px\" align=\"center\" valign=\"top\">\n                ");
if(!prescriptDrug.isDiscontinued())
                {
               	 if (prescriptDrug.getRemoteFacilityId()==null)
               	 {

					if(securityManager.hasWriteAccess("_rx",roleName$,true)) {

                
      out.write("\n                	<a id=\"discont_");
      out.print(prescriptIdInt);
      out.write("\" href=\"javascript:void(0);\" onclick=\"Discontinue(event,this);\" ");
      out.print(styleColor);
      out.write(" >Discon</a>\n                ");
 }
               	 }
                }else{
      out.write("\n                  ");
      out.print(prescriptDrug.getArchivedReason());
      out.write("\n                ");
}
      out.write("\n            </td>\n  ");
      out.write("\n            <td style=\"vertical-align:top;\">\n            	");

            		List<DrugReason> drugReasons  = drugReasonDao.getReasonsForDrugID(prescriptDrug.getId(),true);

            		if (prescriptDrug.getRemoteFacilityId()==null && securityManager.hasWriteAccess("_rx",roleName$,true) )
            		{
            			
      out.write("\n			           	 	<a href=\"javascript:void(0);\"  onclick=\"popupRxReasonWindow(");
      out.print(patient.getDemographicNo());
      out.write(',');
      out.print(prescriptIdInt);
      out.write(");\"  title=\"");
      out.print(displayDrugReason(codingSystemManager,drugReasons,true) );
      out.write("\">\n            			");

            		}
            	
      out.write("\n            	");
      out.print(StringUtils.maxLenString(displayDrugReason(codingSystemManager,drugReasons,false), 4, 3, StringUtils.ELLIPSIS));
      out.write("\n				");

		      		if (prescriptDrug.getRemoteFacilityId()==null  && securityManager.hasWriteAccess("_rx",roleName$,true))
		      		{
		      			
      out.write("\n			            	</a>\n            			");

            		}
				
      out.write("\n            </td>\n  ");
      out.write("\n            ");

            Boolean past_med = prescriptDrug.getPastMed();
            
      out.write("\n\n            <td align=\"center\" valign=\"top\">\n               	");
 if( past_med == null) { 
      out.write("\n        			unk\n        		");
 } else if(past_med) { 
      out.write("\n        			yes\n        		");
 } else { 
      out.write("\n        			no\n        		");
 } 
      out.write("\n            </td>\n\n			");
if(securityManager.hasWriteAccess("_rx",roleName$,true)) {
      out.write("\n            <td width=\"10px\" align=\"center\" valign=\"top\">\n            	");

            		if (prescriptDrug.getRemoteFacilityId()==null)
            		{
            			
      out.write("\n		                <a href=\"javascript:void(0);\" title=\"Annotation\" onclick=\"window.open('../annotation/annotation.jsp?display=");
      out.print(annotation_display);
      out.write("&amp;table_id=");
      out.print(prescriptIdInt);
      out.write("&amp;demo=");
      out.print(bean.getDemographicNo());
      out.write("&amp;drugSpecial=");
      out.print(StringEscapeUtils.escapeJavaScript(specialText));
      out.write("','anwin','width=400,height=500');\">\n		                    ");
if(!isPrevAnnotation){
      out.write(" <img src=\"../images/notes.gif\" alt=\"rxAnnotation\" height=\"16\" width=\"13\" border=\"0\">");
} else{
      out.write("<img src=\"../images/filledNotes.gif\" height=\"16\" width=\"13\" alt=\"rxFilledNotes\" border=\"0\"> ");
}
      out.write("</a>\n            			");

            		}
            	
      out.write("\n            </td>\n            ");
 } 
      out.write("\n\n            <td width=\"10px\" align=\"center\" valign=\"top\">\n                ");

                if (prescriptDrug.getRemoteFacilityName() != null){ 
      out.write("\n                    <span class=\"external\">");
      out.print(prescriptDrug.getRemoteFacilityName());
      out.write("</span>\n                ");
}else if(  prescriptDrug.getOutsideProviderName() !=null && !prescriptDrug.getOutsideProviderName().equals("")  ){
      out.write("\n                    <span class=\"external\">");
      out.print(prescriptDrug.getOutsideProviderName());
      out.write("</span>\n                ");
}else{
      out.write("\n                    local\n                ");
}
      out.write("\n\n\n            </td>\n\n			<td align=\"center\" valign=\"top\">\n				");

					boolean hideCpp = prescriptDrug.getHideFromCpp();
					String checked="";
					if(hideCpp) {
						checked="checked=\"checked\"";
					}
				
      out.write("\n				<input type=\"checkbox\" id=\"hidecpp_");
      out.print(prescriptIdInt);
      out.write('"');
      out.write(' ');
      out.print(checked);
      out.write("/>\n			</td>\n\n			");
if(OscarProperties.getInstance().getProperty("rx.enable_internal_dispensing","false").equals("true")) {
      out.write("\n			<td align=\"center\" valign=\"top\">\n				");

					if(prescriptDrug.getDispenseInternal() != null && prescriptDrug.getDispenseInternal() == true ) {
						if(securityManager.hasWriteAccess("_dispensing",roleName$,true)) {
							String dispensingStatus = drugDispensingManager.getStatus(prescriptDrug.getId());

				
      out.write("\n					<a href=\"javascript:void(0)\" onclick=\"javascript:popupWindow(720,700,'");
      out.print(request.getContextPath());
      out.write("/oscarRx/Dispense.do?method=view&id=");
      out.print(prescriptDrug.getId());
      out.write("','Dispense");
      out.print(prescriptIdInt );
      out.write("'); return false;\">Dispense (");
      out.print(dispensingStatus);
      out.write(")</a>\n				");

					} }
				
      out.write("\n			</td>\n			");
 } 
      out.write("\n\n			<td nowrap=\"nowrap\" align=\"center\" valign=\"top\">\n				");
if(!(prescriptDrugs.get(prescriptDrugs.size()-1) == prescriptDrug)) {
      out.write("\n				<img border=\"0\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/icon_down_sort_arrow.png\" onclick=\"moveDrugDown(");
      out.print(prescriptDrug.getId() );
      out.write(',');
      out.print(prescriptDrugs.get(x+1).getId() );
      out.write(',');
      out.print(prescriptDrug.getDemographicId());
      out.write(");return false;\"/>\n				");
 } 
      out.write("\n				");
if(!(prescriptDrugs.get(0) == prescriptDrug)) {
      out.write("\n				<img border=\"0\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/icon_up_sort_arrow.png\" onclick=\"moveDrugUp(");
      out.print(prescriptDrug.getId() );
      out.write(',');
      out.print(prescriptDrugs.get(x-1).getId() );
      out.write(',');
      out.print(prescriptDrug.getDemographicId());
      out.write(");return false;\"/>\n				");
} 
      out.write("\n			</td>\n        </tr>\n        <script>\nEvent.observe('hidecpp_");
      out.print(prescriptIdInt);
      out.write("', 'change', function(event) {\n	var val = $('hidecpp_");
      out.print(prescriptIdInt);
      out.write("').checked;\n	new Ajax.Request('");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("/oscarRx/hideCpp.do?method=update&prescriptId=");
      out.print(prescriptIdInt);
      out.write("&value='+val, {\n		  method: 'get',\n		  onSuccess: function(transport) {\n		  }\n		});\n\n});\n\n</script>\n        ");
}
      out.write("\n    </table>\n\n</div>\n        <br>\n\n\n        <script type=\"text/javascript\">\nsortables_init();\n            </script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_logic_005fnotPresent_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:notPresent
    org.apache.struts.taglib.logic.NotPresentTag _jspx_th_logic_005fnotPresent_005f0 = (org.apache.struts.taglib.logic.NotPresentTag) _005fjspx_005ftagPool_005flogic_005fnotPresent_0026_005fscope_005fname.get(org.apache.struts.taglib.logic.NotPresentTag.class);
    _jspx_th_logic_005fnotPresent_005f0.setPageContext(_jspx_page_context);
    _jspx_th_logic_005fnotPresent_005f0.setParent(null);
    // /oscarRx/ListDrugs.jsp(52,0) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_logic_005fnotPresent_005f0.setName("RxSessionBean");
    // /oscarRx/ListDrugs.jsp(52,0) name = scope type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_logic_005fnotPresent_005f0.setScope("session");
    int _jspx_eval_logic_005fnotPresent_005f0 = _jspx_th_logic_005fnotPresent_005f0.doStartTag();
    if (_jspx_eval_logic_005fnotPresent_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n    ");
        if (_jspx_meth_logic_005fredirect_005f0(_jspx_th_logic_005fnotPresent_005f0, _jspx_page_context))
          return true;
        out.write('\n');
        int evalDoAfterBody = _jspx_th_logic_005fnotPresent_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_logic_005fnotPresent_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005flogic_005fnotPresent_0026_005fscope_005fname.reuse(_jspx_th_logic_005fnotPresent_005f0);
    return false;
  }

  private boolean _jspx_meth_logic_005fredirect_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fnotPresent_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:redirect
    org.apache.struts.taglib.logic.RedirectTag _jspx_th_logic_005fredirect_005f0 = (org.apache.struts.taglib.logic.RedirectTag) _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody.get(org.apache.struts.taglib.logic.RedirectTag.class);
    _jspx_th_logic_005fredirect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_logic_005fredirect_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotPresent_005f0);
    // /oscarRx/ListDrugs.jsp(53,4) name = href type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_logic_005fredirect_005f0.setHref("error.html");
    int _jspx_eval_logic_005fredirect_005f0 = _jspx_th_logic_005fredirect_005f0.doStartTag();
    if (_jspx_th_logic_005fredirect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody.reuse(_jspx_th_logic_005fredirect_005f0);
    return false;
  }

  private boolean _jspx_meth_logic_005fequal_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fpresent_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:equal
    org.apache.struts.taglib.logic.EqualTag _jspx_th_logic_005fequal_005f0 = (org.apache.struts.taglib.logic.EqualTag) _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname.get(org.apache.struts.taglib.logic.EqualTag.class);
    _jspx_th_logic_005fequal_005f0.setPageContext(_jspx_page_context);
    _jspx_th_logic_005fequal_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fpresent_005f0);
    // /oscarRx/ListDrugs.jsp(58,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_logic_005fequal_005f0.setName("bean");
    // /oscarRx/ListDrugs.jsp(58,4) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_logic_005fequal_005f0.setProperty("valid");
    // /oscarRx/ListDrugs.jsp(58,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_logic_005fequal_005f0.setValue("false");
    int _jspx_eval_logic_005fequal_005f0 = _jspx_th_logic_005fequal_005f0.doStartTag();
    if (_jspx_eval_logic_005fequal_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n        ");
        if (_jspx_meth_logic_005fredirect_005f1(_jspx_th_logic_005fequal_005f0, _jspx_page_context))
          return true;
        out.write("\n    ");
        int evalDoAfterBody = _jspx_th_logic_005fequal_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_logic_005fequal_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005flogic_005fequal_0026_005fvalue_005fproperty_005fname.reuse(_jspx_th_logic_005fequal_005f0);
    return false;
  }

  private boolean _jspx_meth_logic_005fredirect_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_logic_005fequal_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:redirect
    org.apache.struts.taglib.logic.RedirectTag _jspx_th_logic_005fredirect_005f1 = (org.apache.struts.taglib.logic.RedirectTag) _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody.get(org.apache.struts.taglib.logic.RedirectTag.class);
    _jspx_th_logic_005fredirect_005f1.setPageContext(_jspx_page_context);
    _jspx_th_logic_005fredirect_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fequal_005f0);
    // /oscarRx/ListDrugs.jsp(59,8) name = href type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_logic_005fredirect_005f1.setHref("error.html");
    int _jspx_eval_logic_005fredirect_005f1 = _jspx_th_logic_005fredirect_005f1.doStartTag();
    if (_jspx_th_logic_005fredirect_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody.reuse(_jspx_th_logic_005fredirect_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /oscarRx/ListDrugs.jsp(62,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /oscarRx/ListDrugs.jsp(62,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/oscarRx/ListDrugs.jsp(62,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f0 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f0.setParent(null);
    // /oscarRx/ListDrugs.jsp(105,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f0.setKey("SearchDrug.msgRxDate");
    int _jspx_eval_bean_005fmessage_005f0 = _jspx_th_bean_005fmessage_005f0.doStartTag();
    if (_jspx_th_bean_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f1 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f1.setParent(null);
    // /oscarRx/ListDrugs.jsp(108,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f1.setKey("SearchDrug.msgPrescription");
    int _jspx_eval_bean_005fmessage_005f1 = _jspx_th_bean_005fmessage_005f1.doStartTag();
    if (_jspx_th_bean_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f2 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f2.setParent(null);
    // /oscarRx/ListDrugs.jsp(110,47) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f2.setKey("SearchDrug.msgReprescribe");
    int _jspx_eval_bean_005fmessage_005f2 = _jspx_th_bean_005fmessage_005f2.doStartTag();
    if (_jspx_th_bean_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f3 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f3.setParent(null);
    // /oscarRx/ListDrugs.jsp(112,48) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f3.setKey("SearchDrug.msgDelete");
    int _jspx_eval_bean_005fmessage_005f3 = _jspx_th_bean_005fmessage_005f3.doStartTag();
    if (_jspx_th_bean_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f3);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f4 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f4.setParent(null);
    // /oscarRx/ListDrugs.jsp(116,47) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f4.setKey("SearchDrug.msgDiscontinue");
    int _jspx_eval_bean_005fmessage_005f4 = _jspx_th_bean_005fmessage_005f4.doStartTag();
    if (_jspx_th_bean_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f4);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f5 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f5.setParent(null);
    // /oscarRx/ListDrugs.jsp(117,42) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f5.setKey("SearchDrug.msgReason_help");
    int _jspx_eval_bean_005fmessage_005f5 = _jspx_th_bean_005fmessage_005f5.doStartTag();
    if (_jspx_th_bean_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f5);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f6 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f6.setParent(null);
    // /oscarRx/ListDrugs.jsp(117,94) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f6.setKey("SearchDrug.msgReason");
    int _jspx_eval_bean_005fmessage_005f6 = _jspx_th_bean_005fmessage_005f6.doStartTag();
    if (_jspx_th_bean_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f6);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f7 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f7.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f7.setParent(null);
    // /oscarRx/ListDrugs.jsp(118,47) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f7.setKey("SearchDrug.msgPastMed");
    int _jspx_eval_bean_005fmessage_005f7 = _jspx_th_bean_005fmessage_005f7.doStartTag();
    if (_jspx_th_bean_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f7);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f8 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f8.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f8.setParent(null);
    // /oscarRx/ListDrugs.jsp(122,31) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f8.setKey("SearchDrug.msgLocationPrescribed");
    int _jspx_eval_bean_005fmessage_005f8 = _jspx_th_bean_005fmessage_005f8.doStartTag();
    if (_jspx_th_bean_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f8);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f9 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f9.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f9.setParent(null);
    // /oscarRx/ListDrugs.jsp(123,38) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f9.setKey("SearchDrug.msgHideCPP_help");
    int _jspx_eval_bean_005fmessage_005f9 = _jspx_th_bean_005fmessage_005f9.doStartTag();
    if (_jspx_th_bean_005fmessage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f9);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f10 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f10.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f10.setParent(null);
    // /oscarRx/ListDrugs.jsp(123,88) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f10.setKey("SearchDrug.msgHideCPP");
    int _jspx_eval_bean_005fmessage_005f10 = _jspx_th_bean_005fmessage_005f10.doStartTag();
    if (_jspx_th_bean_005fmessage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f10);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f11 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f11.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f11.setParent(null);
    // /oscarRx/ListDrugs.jsp(125,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f11.setKey("SearchDrug.msgDispense");
    int _jspx_eval_bean_005fmessage_005f11 = _jspx_th_bean_005fmessage_005f11.doStartTag();
    if (_jspx_th_bean_005fmessage_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f11);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f12 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f12.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f12.setParent(null);
    // /oscarRx/ListDrugs.jsp(225,80) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f12.setKey("oscarRx.Prescription.changeDrugShortTerm");
    int _jspx_eval_bean_005fmessage_005f12 = _jspx_th_bean_005fmessage_005f12.doStartTag();
    if (_jspx_th_bean_005fmessage_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f12);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f13 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f13.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f13.setParent(null);
    // /oscarRx/ListDrugs.jsp(226,40) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f13.setKey("global.yes");
    int _jspx_eval_bean_005fmessage_005f13 = _jspx_th_bean_005fmessage_005f13.doStartTag();
    if (_jspx_th_bean_005fmessage_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f13);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f14 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f14.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f14.setParent(null);
    // /oscarRx/ListDrugs.jsp(238,99) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f14.setKey("oscarRx.Prescription.changeDrugLongTerm");
    int _jspx_eval_bean_005fmessage_005f14 = _jspx_th_bean_005fmessage_005f14.doStartTag();
    if (_jspx_th_bean_005fmessage_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f14);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f15 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f15.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f15.setParent(null);
    // /oscarRx/ListDrugs.jsp(239,48) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f15.setKey("global.no");
    int _jspx_eval_bean_005fmessage_005f15 = _jspx_th_bean_005fmessage_005f15.doStartTag();
    if (_jspx_th_bean_005fmessage_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f15);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /oscarRx/ListDrugs.jsp(410,19) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
