/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2026-06-03 23:02:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.oscarRx;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import oscar.oscarRx.data.*;
import java.text.DateFormatSymbols;
import oscar.oscarRx.pageUtil.*;
import java.io.*;
import org.apache.xmlrpc.*;
import oscar.util.StringUtils;
import java.util.Random;

public final class MyDrugrefDisplay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {



     String getCommentDisplay(Hashtable h){
         StringBuffer ret = new StringBuffer();
         //key:comments val [{created_at=Fri Apr 04 14:35:10 EDT 2008, name=Re: APO-WARFARIN 10MG, id=4053, post_id=133, author=Guest, goat=true, created_by=7, body=i disagree , updated_at=Fri Apr 04 14:35:10 EDT 2008}]  class : java.util.Vector
//key:type val Warning  class : java.lang.String
         if (h != null){
             Boolean thumbs = (Boolean) h.get("goat");
             boolean thumb = true;
             if(thumbs != null && thumbs.booleanValue()){
                 ret.append("+");
             }else{
                 ret.append("-");
             }

             ret.append("From: "+h.get("author")+", "+h.get("body"));
             //author=Guest, goat=true, created_by=7, body=i disagree
         }
         return ret.toString();
     }

      String s(Object o){
          String ret ="";

          if(o != null && o instanceof String){
              return (String) o;
          }

          return ret;
      }


       String outputHtmlClass(boolean trustedResource, boolean hideResource){
           if (!trustedResource && hideResource){
               return "class=\"untrustedResource hiddenResource\"";
           }else if (trustedResource && hideResource){
               return "class=\"hiddenResource\"";
           }else if (!trustedResource && !hideResource){
               return "class=\"untrustedResource\"";
           }
           return "";
       }


       boolean trusted(Object o){
           boolean b = false;
           if (o != null && o instanceof Boolean){
              Boolean c  = (Boolean) o;
              b = c.booleanValue();
           }
           return b;
       }

       long getTime(Object o){
            Date d = (Date) o;
            return d.getTime();
        }
        String getDateMonthYear(Date d){
          if(d==null) return "";
          
          Calendar cal=Calendar.getInstance();
          cal.setTime(d);
          Integer date=cal.get(Calendar.DATE);
          Integer month=cal.get(Calendar.MONTH);
          Integer year=cal.get(Calendar.YEAR);
          String[] shortMonths = new DateFormatSymbols().getShortMonths();
          String shortMonth=shortMonths[month];
          String retStr=date+"-"+shortMonth+"-"+year;
          return retStr;
        }
	String significance(String s){
       Hashtable h = new Hashtable();
       h.put("1","minor");
       h.put("2","moderate");
       h.put("3","major");
       h.put(" ","unknown");

       String retval = (String) h.get(s);
        if (retval == null) {retval = "unknown";}
        return retval;
   }

   String evidence(String s){
       Hashtable h = new Hashtable();
       h.put("P","Poor");
       h.put("F","Fair");
       h.put("G","Good");
       h.put(" ","Unknown");

       String retval = (String) h.get(s);
        if (retval == null) {retval = "Unknown";}
        return retval;
   }


   String sigColor(String s){
       Hashtable h = new Hashtable();
       h.put("1","yellow");
       h.put("2","orange");
       h.put("3","red");
       h.put(" ","greenyellow");

       String retval = (String) h.get(s);
        if (retval == null) {retval = "greenyellow";}
        return retval;
   }

   String severityOfReaction(String s){
       Hashtable h = new Hashtable();
       h.put("1","Mild");
       h.put("2","Moderate");
       h.put("3","Severe");

       String retval = (String) h.get(s);
       if (retval == null) {retval = "Unknown";}
       return retval;
   }

   String severityOfReactionColor(String s){
       Hashtable h = new Hashtable();
       h.put("1","yellow");
       h.put("2","orange");
       h.put("3","red");

       String retval = (String) h.get(s);
       if (retval == null) {retval = "red";}
       return retval;
   }

   String onSetOfReaction(String s){
       Hashtable h = new Hashtable();
       h.put("1","Immediate");
       h.put("2","Gradual");
       h.put("3","Slow");

       String retval = (String) h.get(s);
       if (retval == null) {retval = "Unknown";}
       return retval;
   }

   String displayKeys(Hashtable ht) {
       StringBuffer sb = new StringBuffer();
       if (ht != null){
            for (Object o :ht.keySet()){
                String s  = "key:"+o+" val "+ht.get(o)+"  class : "+ht.get(o).getClass().getName();
                sb.append(s);
            }
       }
       return sb.toString();
   }



  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/security.tld", Long.valueOf(1780193738112L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(11);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("org.apache.xmlrpc");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("oscar.oscarRx.data");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("oscar.oscarRx.pageUtil");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.text.DateFormatSymbols");
    _jspx_imports_classes.add("oscar.util.StringUtils");
    _jspx_imports_classes.add("java.util.Random");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n\n\n\n");

    String roleName$ = (String)session.getAttribute("userrole") + "," + (String) session.getAttribute("user");
    boolean authed=true;

      out.write('\n');
      //  security:oscarSec
      oscar.login.tld.SecurityTag _jspx_th_security_005foscarSec_005f0 = (oscar.login.tld.SecurityTag) _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.get(oscar.login.tld.SecurityTag.class);
      _jspx_th_security_005foscarSec_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005foscarSec_005f0.setParent(null);
      // /oscarRx/MyDrugrefDisplay.jsp(61,0) name = roleName type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setRoleName(roleName$);
      // /oscarRx/MyDrugrefDisplay.jsp(61,0) name = objectName type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setObjectName("_rx");
      // /oscarRx/MyDrugrefDisplay.jsp(61,0) name = rights type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setRights("r");
      // /oscarRx/MyDrugrefDisplay.jsp(61,0) name = reverse type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setReverse(true);
      int _jspx_eval_security_005foscarSec_005f0 = _jspx_th_security_005foscarSec_005f0.doStartTag();
      if (_jspx_eval_security_005foscarSec_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write('\n');
        out.write('	');
authed=false; 
        out.write('\n');
        out.write('	');
response.sendRedirect("../securityError.jsp?type=_rx");
        out.write('\n');
      }
      if (_jspx_th_security_005foscarSec_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.reuse(_jspx_th_security_005foscarSec_005f0);
      out.write('\n');

	if(!authed) {
		return;
	}

      out.write("\n\n<div id=\"showHideTotal\"></div>\n");

    Vector<Hashtable> warnings = (Vector)request.getAttribute("warnings");
    Hashtable hiddenResources = (Hashtable) request.getSession().getAttribute("hideResources");
    if ( warnings != null && warnings.size() > 0){

        int untrustedRes = 0;
        int hiddenRes = 0;
        Random rnd=new Random();
        for (Hashtable ht: warnings){
            Vector<Hashtable> commentsVec = (Vector) ht.get("comments");
            displayKeys(ht);

            boolean trustedResource = trusted(ht.get("trusted"));
            boolean hideResource = false;

            String interactStr=(String)ht.get("interactStr");
            if(interactStr==null) interactStr="";
            if (hiddenResources != null ) {
                hideResource = hiddenResources.containsKey("mydrugref"+ht.get("id"));
            }

            String hidden ="";
            if (!trustedResource){
                untrustedRes++;
                hidden ="display:none;";
            }
            if (hideResource){
                hiddenRes++;
                hidden ="display:none;";
            }
            String showHidden="";
            if(hidden.equals("display:none;"));
            else
                showHidden="display:none;";
            String bodyStr=(String)ht.get("body");
            int rand=Math.abs(rnd.nextInt());
            String elementId=ht.get("id")+"."+getTime(ht.get("updated_at"));
          Date lastUpdateTime=(Date)ht.get("updated_at");
          String lastUpdateDate=getDateMonthYear(lastUpdateTime);
            
      out.write("\n\n<div id=\"");
      out.print(elementId);
      out.write('"');
      out.write('\n');
      out.write('	');
      out.print(outputHtmlClass(trustedResource,hideResource));
      out.write("\n	style=\"font-size: 9pt;");
      out.print(hidden);
      out.write("background-color:");
      out.print(sigColor(""+ht.get("significance")));
      out.write(";margin-right:3px;margin-left:3px;margin-top:2px;padding-left:3px;padding-top:3px;padding-bottom:3px;\">\n<span style=\"float: right;\"><a href=\"javascript:void(0);\"\n	onclick=\"HideW('");
      out.print(ht.get("id"));
      out.write('.');
      out.print(getTime(ht.get("updated_at")));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(ht.get("id"));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(getTime(ht.get("updated_at")));
      out.write("')\">Hide</a></span>\n        ");
      out.print(interactStr);
      out.write("<br/>\n<b>");
      out.print(ht.get("name"));
      out.write("</b> From:");
      out.print(s(ht.get("author")));
      out.write(" <br/>\nLast Update:");
      out.print(s(lastUpdateDate));
      out.write("<br/>\n\n");
if(bodyStr.length() > 90){
      out.write('\n');
      out.print(((String)ht.get("body")).substring(0,90));
      out.write("<a id=\"addText_");
      out.print(rand);
      out.write("\" style=\"display:none;padding:2px;\">");
      out.print(((String)ht.get("body")).substring(90));
      out.write("\n</a>\n<div><a href=\"javascript:void(0);\" id=\"addTextWord_");
      out.print(rand);
      out.write("\" onclick=\"showAddText('");
      out.print(rand);
      out.write("');\"><span>more</span></a></div>\n\n");
} else{
      out.write('\n');
      out.print(ht.get("body"));
      out.write('\n');
}
      out.write("\n     <br/><!--br/>");
      out.write("<br/-->\n");
 String ref = (String)ht.get("reference");
      out.write(' ');
if (commentsVec != null && commentsVec.size() > 0){ 
      out.write("\n<a style=\"float: right;\" href=\"javascript:void(0);\"\n	onclick=\"$('comm.");
      out.print(ht.get("id"));
      out.write('.');
      out.print(getTime(ht.get("updated_at")));
      out.write("').toggle();\">comments</a>\n");
}
      out.write(' ');
      out.write('(');
      out.print(ht.get("evidence"));
      out.write(") &nbsp;Reference: <a href=\"");
      out.print(ht.get("reference"));
      out.write("\" target=\"_blank\">");
      out.print( StringUtils.maxLenString(ref, 51, 50, "...") );
      out.write("</a>\n\n\n\n");
if (commentsVec != null && commentsVec.size() > 0){
     
      out.write(" <!--a style=\"float:right;\" href=\"javascript:void(0);\" onclick=\"$('comm.");
      out.print(ht.get("id"));
      out.write('.');
      out.print(getTime(ht.get("updated_at")));
      out.write("').toggle();\">comments</a-->\n<fieldset style=\"border: 1px solid white; display: none; padding: 2px;\"	id=\"comm.");
      out.print(ht.get("id"));
      out.write('.');
      out.print(getTime(ht.get("updated_at")));
      out.write("\">\n<legend>Comments</legend> ");
for(Hashtable comment : commentsVec){ 
      out.write("\n<div>");
      out.print( getCommentDisplay( comment ) );
      out.write("</div>\n");
}
      out.write("\n</fieldset>\n");
}
      out.write("\n</div>\n<div id=\"show_");
      out.print(elementId);
      out.write("\" style=\"text-align: right; ");
      out.print(showHidden);
      out.write("font-size: 9pt; background-color:");
      out.print(sigColor(""+ht.get("significance")));
      out.write(";margin-right:3px;margin-left:3px;margin-top:2px;padding-left:3px;padding-top:3px;padding-bottom:3px;\">\n    <a  href=\"javascript:void(0);\" onclick=\"ShowW('");
      out.print(elementId);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(ht.get("id"));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(getTime(ht.get("updated_at")));
      out.write("');\">Show</a>\n</div>\n");

        }
        if (untrustedRes > 0 ){ 
      out.write("\n<div><a href=\"javascript:void(0);\" onclick=\"showUntrustedRes();\"><span\n	id=\"showUntrustedResWord\">show</span> ");
      out.print(untrustedRes);
      out.write(" untrusted\nresources</a></div>\n");
}


      out.write("\n    ");
}else if(warnings == null){ 
      out.write("\n<div>MyDrug to MyDrug Warning Service not available</div>\n");
  }   
      out.write("\n\n<script type=\"text/javascript\">\n    new Ajax.Updater('showHideTotal','updateMyDrugrefResource.jsp',{method:'get',onSuccess:function(transport){\n                oscarLog(\"updated showHideTotal \");\n            }});\n</script>\n\n\n\n");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
