/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2026-06-02 19:00:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.provider;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.oscarehr.util.MiscUtils;
import org.oscarehr.util.LoggedInInfo;
import org.oscarehr.PMmodule.web.utils.UserRoleUtils;
import org.oscarehr.util.SessionConstants;
import java.util.*;
import java.net.*;
import oscar.util.*;
import oscar.OscarProperties;

public final class providercontrol_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1780193738074L));
    _jspx_dependants.put("/WEB-INF/caisi-tag.tld", Long.valueOf(1780193737744L));
    _jspx_dependants.put("jar:file:/home/dmoniz/projects/oscar/catalina_base/webapps/oscar/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
    _jspx_dependants.put("/WEB-INF/security.tld", Long.valueOf(1780193738112L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.net");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("oscar.util");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(7);
    _jspx_imports_classes.add("oscar.OscarProperties");
    _jspx_imports_classes.add("org.oscarehr.util.MiscUtils");
    _jspx_imports_classes.add("org.oscarehr.util.LoggedInInfo");
    _jspx_imports_classes.add("org.oscarehr.PMmodule.web.utils.UserRoleUtils");
    _jspx_imports_classes.add("org.oscarehr.util.SessionConstants");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcaisi_005fisModuleLoad_0026_005fmoduleName;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcaisi_005fisModuleLoad_0026_005fmoduleName = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcaisi_005fisModuleLoad_0026_005fmoduleName.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"errorpage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n\n\n\n\n\n\n\n\n\n\n");
      //  caisi:isModuleLoad
      oscar.caisi.IsModuleLoadTag _jspx_th_caisi_005fisModuleLoad_005f0 = (oscar.caisi.IsModuleLoadTag) _005fjspx_005ftagPool_005fcaisi_005fisModuleLoad_0026_005fmoduleName.get(oscar.caisi.IsModuleLoadTag.class);
      _jspx_th_caisi_005fisModuleLoad_005f0.setPageContext(_jspx_page_context);
      _jspx_th_caisi_005fisModuleLoad_005f0.setParent(null);
      // /provider/providercontrol.jsp(38,0) name = moduleName type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_caisi_005fisModuleLoad_005f0.setModuleName("caisi");
      int _jspx_eval_caisi_005fisModuleLoad_005f0 = _jspx_th_caisi_005fisModuleLoad_005f0.doStartTag();
      if (_jspx_eval_caisi_005fisModuleLoad_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\n');

	LoggedInInfo loggedInInfo=LoggedInInfo.getLoggedInInfoFromSession(request);
    String isOscar = request.getParameter("infirmaryView_isOscar");
    if (session.getAttribute("infirmaryView_isOscar")==null) isOscar="false";
    if (isOscar!=null) session.setAttribute("infirmaryView_isOscar", isOscar);
    if(request.getParameter(SessionConstants.CURRENT_PROGRAM_ID) != null) {
    	session.setAttribute(SessionConstants.CURRENT_PROGRAM_ID,request.getParameter(SessionConstants.CURRENT_PROGRAM_ID));
    	org.caisi.core.web.InfirmAction.updateCurrentProgram(request.getParameter(SessionConstants.CURRENT_PROGRAM_ID), loggedInInfo.getLoggedInProviderNo());
    }
    session.setAttribute("infirmaryView_OscarURL",request.getRequestURL());


          if (_jspx_meth_c_005fimport_005f0(_jspx_th_caisi_005fisModuleLoad_005f0, _jspx_page_context))
            return;
          out.write('\n');
          int evalDoAfterBody = _jspx_th_caisi_005fisModuleLoad_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_caisi_005fisModuleLoad_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fcaisi_005fisModuleLoad_0026_005fmoduleName.reuse(_jspx_th_caisi_005fisModuleLoad_005f0);
      out.write('\n');
      out.write('\n');

    if(session.getAttribute("userrole") == null ) {
   	 	MiscUtils.getLogger().error("userrole is null? logging user out");
        response.sendRedirect("../logout.jsp");
        return;
    }
    String roleName$ = (String)session.getAttribute("userrole") + "," + (String) session.getAttribute("user");

    if(roleName$.indexOf(UserRoleUtils.Roles.er_clerk.name()) != -1) {
        response.sendRedirect("er_clerk.jsp");
        return;
    }

    if(roleName$.indexOf("Vaccine Provider") != -1) {
        response.sendRedirect("vaccine_provider.jsp");
        return;
    }

      out.write('\n');
      out.write('\n');
      //  security:oscarSec
      oscar.login.tld.SecurityTag _jspx_th_security_005foscarSec_005f0 = (oscar.login.tld.SecurityTag) _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.get(oscar.login.tld.SecurityTag.class);
      _jspx_th_security_005foscarSec_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005foscarSec_005f0.setParent(null);
      // /provider/providercontrol.jsp(72,0) name = roleName type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setRoleName(roleName$);
      // /provider/providercontrol.jsp(72,0) name = objectName type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setObjectName("_appointment");
      // /provider/providercontrol.jsp(72,0) name = rights type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setRights("r");
      // /provider/providercontrol.jsp(72,0) name = reverse type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setReverse(true);
      int _jspx_eval_security_005foscarSec_005f0 = _jspx_th_security_005foscarSec_005f0.doStartTag();
      if (_jspx_eval_security_005foscarSec_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write('\n');
        out.write('	');

        if (true)
        {
      	  	MiscUtils.getLogger().error("wrong role? logging user out");
            response.sendRedirect("../logout.jsp");
            return;
        }
    
        out.write('\n');
      }
      if (_jspx_th_security_005foscarSec_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.reuse(_jspx_th_security_005foscarSec_005f0);
      out.write('\n');
      out.write('\n');

    if(session.getAttribute("user") == null) {
 	  	MiscUtils.getLogger().error("missing session user? logging user out");
        response.sendRedirect("../logout.jsp");
        return;
    }

	//preserving context for new ui this is temp until schedule is created in new ui
	String router = "";
	String record = "";
	String module = "";
	//retained date as well  
	
	if(request.getParameter("record")!=null){
		record="record="+request.getParameter("record");
	}
	
	if(request.getParameter("module")!=null){
		module="module=" + request.getParameter("module");
	}
	
	if(!record.equals("") && !module.equals("")){
		router = "&" + record + "&" + module;
	}else if(record.equals("") && !module.equals("")){
		router = "&" + module;
	}
	//preserving context ---end

    if(request.getParameter("year")==null && request.getParameter("month")==null && request.getParameter("day")==null && request.getParameter("displaymode")==null && request.getParameter("dboperation")==null) {
        GregorianCalendar now=new GregorianCalendar();
        int nowYear = now.get(Calendar.YEAR);
        int nowMonth = now.get(Calendar.MONTH)+1 ; //be care for the month +-1
        int nowDay = now.get(Calendar.DAY_OF_MONTH);
        OscarProperties props = OscarProperties.getInstance();
        String caisiView = null;
        caisiView = request.getParameter("GoToCaisiViewFromOscarView");
        boolean viewAll_bool = true;  // false, restore original schedule view on appointment screen
        
        if (props.getProperty("default_schedule_viewall", "").startsWith("false") )
            viewAll_bool = false;
            
        if(caisiView!=null && "true".equals(caisiView)) {
        	if (viewAll_bool){
	        	response.sendRedirect("./providercontrol.jsp?GoToCaisiViewFromOscarView=true&year="+nowYear+"&month="+(nowMonth)+"&day="+(nowDay)+"&view=0&displaymode=day&dboperation=searchappointmentday&viewall=1");
	        	return;
        	}
        	else{
	        	response.sendRedirect("./providercontrol.jsp?GoToCaisiViewFromOscarView=true&year="+nowYear+"&month="+(nowMonth)+"&day="+(nowDay)+"&view=0&displaymode=day&dboperation=searchappointmentday&viewall=0");
	        	return;
	        }
        }
        if (viewAll_bool){
        	       	
	        response.sendRedirect("./providercontrol.jsp?year="+nowYear+"&month="+(nowMonth)+"&day="+(nowDay)+"&view=0&displaymode=day&dboperation=searchappointmentday&viewall=1" + router);
	        return;
	    }
	    else{
	    	response.sendRedirect("./providercontrol.jsp?year="+nowYear+"&month="+(nowMonth)+"&day="+(nowDay)+"&view=0&displaymode=day&dboperation=searchappointmentday&viewall=0" + router);
	        return;
	    }
	        
    }

    //associate each operation with an output JSP file - displaymode
    String[][] opToFile = new String[][] {
            {"day" , "appointmentprovideradminday.jsp"},
            {"month" , "appointmentprovideradminmonth.jsp"},
            {"addstatus" , "provideraddstatus.jsp"},
            {"updatepreference" , "providerupdatepreference.jsp"},
            {"displaymygroup" , "providerdisplaymygroup.jsp"},
            {"encounter" , "providerencounter.jsp"},
            {"encountersingle" , "providerencountersingle.jsp"},
            {"vary" , request.getParameter("displaymodevariable")==null?"":URLDecoder.decode(request.getParameter("displaymodevariable")) },
            {"saveencounter" , "providersaveencounter.jsp"},
            {"savebill" , "providersavebill.jsp"},
            {"savedemographicaccessory" , "providersavedemographicaccessory.jsp"},
            {"encounterhistory" , "providerencounterhistory.jsp"},
            {"savedeletetemplate" , "providertemplate.jsp"},
            {"ar1" , "formar1_99_12.jsp"},
            {"ar2" , "formar2_99_08.jsp"},
            {"newgroup" , "providernewgroup.jsp"},
            {"savemygroup" , "providersavemygroup.jsp"}

    };

    // create an operation-to-file dictionary
    UtilDict opToFileDict = new UtilDict();
    opToFileDict.setDef(opToFile);

    // create a request parameter name-to-value dictionary
    UtilDict requestParamDict = new UtilDict();
    requestParamDict.setDef(request);

    // get operation name from request
    String operation = requestParamDict.getDef("displaymode","");

    // redirect to a file associated with operation
    pageContext.forward(opToFileDict.getDef(operation,""));

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_caisi_005fisModuleLoad_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_caisi_005fisModuleLoad_005f0);
    // /provider/providercontrol.jsp(50,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl("/infirm.do?action=getSig");
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    return false;
  }
}
