/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2026-06-02 17:10:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.provider;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import oscar.OscarProperties;

public final class tabAlertsRefresh_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/oscar-tag.tld", Long.valueOf(1780193738112L));
    _jspx_dependants.put("/WEB-INF/struts-bean.tld", Long.valueOf(1780193738112L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("oscar.OscarProperties");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005foscar_005fnewLab_0026_005fproviderNo;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005foscar_005fnewMessage_0026_005fproviderNo;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005foscar_005fnewTickler_0026_005fproviderNo;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005foscar_005fagedConsult_0026_005fproviderNo;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005foscar_005ffilledScratch_0026_005fproviderNo_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005foscar_005fnewLab_0026_005fproviderNo = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005foscar_005fnewMessage_0026_005fproviderNo = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005foscar_005fnewTickler_0026_005fproviderNo = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005foscar_005fagedConsult_0026_005fproviderNo = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005foscar_005ffilledScratch_0026_005fproviderNo_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005foscar_005fnewLab_0026_005fproviderNo.release();
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005foscar_005fnewMessage_0026_005fproviderNo.release();
    _005fjspx_005ftagPool_005foscar_005fnewTickler_0026_005fproviderNo.release();
    _005fjspx_005ftagPool_005foscar_005fagedConsult_0026_005fproviderNo.release();
    _005fjspx_005ftagPool_005foscar_005ffilledScratch_0026_005fproviderNo_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    String curUser_no = (String) session.getAttribute("user");
    String tab = request.getParameter("id");
    
    if (tab.equals("oscar_new_lab")) { 
      out.write('\n');
      out.write('	');
      out.write('\n');
      //  oscar:newLab
      oscar.oscarLab.tld.LabTag _jspx_th_oscar_005fnewLab_005f0 = (oscar.oscarLab.tld.LabTag) _005fjspx_005ftagPool_005foscar_005fnewLab_0026_005fproviderNo.get(oscar.oscarLab.tld.LabTag.class);
      _jspx_th_oscar_005fnewLab_005f0.setPageContext(_jspx_page_context);
      _jspx_th_oscar_005fnewLab_005f0.setParent(null);
      // /provider/tabAlertsRefresh.jsp(34,0) name = providerNo type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_oscar_005fnewLab_005f0.setProviderNo(curUser_no);
      int _jspx_eval_oscar_005fnewLab_005f0 = _jspx_th_oscar_005fnewLab_005f0.doStartTag();
      if (_jspx_eval_oscar_005fnewLab_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_bean_005fmessage_005f0(_jspx_th_oscar_005fnewLab_005f0, _jspx_page_context))
            return;
          int evalDoAfterBody = _jspx_th_oscar_005fnewLab_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_oscar_005fnewLab_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005foscar_005fnewLab_0026_005fproviderNo.reuse(_jspx_th_oscar_005fnewLab_005f0);
      out.write('\n');
  }
    if (tab.equals("oscar_new_msg")) { 
      out.write("\n        ");
      //  oscar:newMessage
      oscar.oscarMessenger.tld.MsgNewMessageTag _jspx_th_oscar_005fnewMessage_005f0 = (oscar.oscarMessenger.tld.MsgNewMessageTag) _005fjspx_005ftagPool_005foscar_005fnewMessage_0026_005fproviderNo.get(oscar.oscarMessenger.tld.MsgNewMessageTag.class);
      _jspx_th_oscar_005fnewMessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_oscar_005fnewMessage_005f0.setParent(null);
      // /provider/tabAlertsRefresh.jsp(37,8) name = providerNo type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_oscar_005fnewMessage_005f0.setProviderNo(curUser_no);
      int _jspx_eval_oscar_005fnewMessage_005f0 = _jspx_th_oscar_005fnewMessage_005f0.doStartTag();
      if (_jspx_eval_oscar_005fnewMessage_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_bean_005fmessage_005f1(_jspx_th_oscar_005fnewMessage_005f0, _jspx_page_context))
            return;
          int evalDoAfterBody = _jspx_th_oscar_005fnewMessage_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_oscar_005fnewMessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005foscar_005fnewMessage_0026_005fproviderNo.reuse(_jspx_th_oscar_005fnewMessage_005f0);
      out.write('\n');
  }
    if (tab.equals("oscar_new_tickler")) { 
      out.write("\n        ");
      //  oscar:newTickler
      oscar.oscarTickler.tld.TicklerTag _jspx_th_oscar_005fnewTickler_005f0 = (oscar.oscarTickler.tld.TicklerTag) _005fjspx_005ftagPool_005foscar_005fnewTickler_0026_005fproviderNo.get(oscar.oscarTickler.tld.TicklerTag.class);
      _jspx_th_oscar_005fnewTickler_005f0.setPageContext(_jspx_page_context);
      _jspx_th_oscar_005fnewTickler_005f0.setParent(null);
      // /provider/tabAlertsRefresh.jsp(40,8) name = providerNo type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_oscar_005fnewTickler_005f0.setProviderNo(curUser_no);
      int _jspx_eval_oscar_005fnewTickler_005f0 = _jspx_th_oscar_005fnewTickler_005f0.doStartTag();
      if (_jspx_eval_oscar_005fnewTickler_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_bean_005fmessage_005f2(_jspx_th_oscar_005fnewTickler_005f0, _jspx_page_context))
            return;
          int evalDoAfterBody = _jspx_th_oscar_005fnewTickler_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_oscar_005fnewTickler_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005foscar_005fnewTickler_0026_005fproviderNo.reuse(_jspx_th_oscar_005fnewTickler_005f0);
      out.write('\n');
  }
    if (tab.equals("oscar_aged_consults")) { 
      out.write("\n        ");
      //  oscar:agedConsult
      oscar.oscarEncounter.oscarConsultationRequest.tld.ConsultTag _jspx_th_oscar_005fagedConsult_005f0 = (oscar.oscarEncounter.oscarConsultationRequest.tld.ConsultTag) _005fjspx_005ftagPool_005foscar_005fagedConsult_0026_005fproviderNo.get(oscar.oscarEncounter.oscarConsultationRequest.tld.ConsultTag.class);
      _jspx_th_oscar_005fagedConsult_005f0.setPageContext(_jspx_page_context);
      _jspx_th_oscar_005fagedConsult_005f0.setParent(null);
      // /provider/tabAlertsRefresh.jsp(43,8) name = providerNo type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_oscar_005fagedConsult_005f0.setProviderNo(curUser_no);
      int _jspx_eval_oscar_005fagedConsult_005f0 = _jspx_th_oscar_005fagedConsult_005f0.doStartTag();
      if (_jspx_eval_oscar_005fagedConsult_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          if (_jspx_meth_bean_005fmessage_005f3(_jspx_th_oscar_005fagedConsult_005f0, _jspx_page_context))
            return;
          int evalDoAfterBody = _jspx_th_oscar_005fagedConsult_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_oscar_005fagedConsult_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005foscar_005fagedConsult_0026_005fproviderNo.reuse(_jspx_th_oscar_005fagedConsult_005f0);
      out.write('\n');
      out.write(' ');
      out.write(' ');
}
    if (!OscarProperties.getInstance().isTorontoRFQ() && tab.equals("oscar_scratch") ) { 
      out.write("\n	<img src='");
      //  oscar:filledScratch
      oscar.scratch.tld.ScratchTag _jspx_th_oscar_005ffilledScratch_005f0 = (oscar.scratch.tld.ScratchTag) _005fjspx_005ftagPool_005foscar_005ffilledScratch_0026_005fproviderNo_005fnobody.get(oscar.scratch.tld.ScratchTag.class);
      _jspx_th_oscar_005ffilledScratch_005f0.setPageContext(_jspx_page_context);
      _jspx_th_oscar_005ffilledScratch_005f0.setParent(null);
      // /provider/tabAlertsRefresh.jsp(46,11) name = providerNo type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_oscar_005ffilledScratch_005f0.setProviderNo(curUser_no);
      int _jspx_eval_oscar_005ffilledScratch_005f0 = _jspx_th_oscar_005ffilledScratch_005f0.doStartTag();
      if (_jspx_th_oscar_005ffilledScratch_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005foscar_005ffilledScratch_0026_005fproviderNo_005fnobody.reuse(_jspx_th_oscar_005ffilledScratch_005f0);
      out.write("' border='0' align=\"absbottom\" title='Scratch Pad'>\n");
  } 
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_bean_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_oscar_005fnewLab_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f0 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_oscar_005fnewLab_005f0);
    // /provider/tabAlertsRefresh.jsp(34,43) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f0.setKey("global.lab");
    int _jspx_eval_bean_005fmessage_005f0 = _jspx_th_bean_005fmessage_005f0.doStartTag();
    if (_jspx_th_bean_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_oscar_005fnewMessage_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f1 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_oscar_005fnewMessage_005f0);
    // /provider/tabAlertsRefresh.jsp(37,55) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f1.setKey("global.msg");
    int _jspx_eval_bean_005fmessage_005f1 = _jspx_th_bean_005fmessage_005f1.doStartTag();
    if (_jspx_th_bean_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_oscar_005fnewTickler_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f2 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_oscar_005fnewTickler_005f0);
    // /provider/tabAlertsRefresh.jsp(40,55) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f2.setKey("global.btntickler");
    int _jspx_eval_bean_005fmessage_005f2 = _jspx_th_bean_005fmessage_005f2.doStartTag();
    if (_jspx_th_bean_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_oscar_005fagedConsult_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f3 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_oscar_005fagedConsult_005f0);
    // /provider/tabAlertsRefresh.jsp(43,56) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f3.setKey("global.con");
    int _jspx_eval_bean_005fmessage_005f3 = _jspx_th_bean_005fmessage_005f3.doStartTag();
    if (_jspx_th_bean_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f3);
    return false;
  }
}
