/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2026-06-03 23:02:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.oscarMDS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import java.util.*;
import org.apache.commons.collections.MultiHashMap;
import org.apache.commons.lang.StringEscapeUtils;
import org.apache.logging.log4j.Logger;
import org.oscarehr.common.dao.OscarLogDao;
import org.oscarehr.common.hl7.v2.oscar_to_oscar.OscarToOscarUtils;
import org.oscarehr.util.MiscUtils;
import org.oscarehr.util.SpringUtils;
import oscar.oscarLab.ca.on.*;
import oscar.oscarMDS.data.*;
import oscar.util.StringUtils;
import oscar.util.UtilDateUtilities;
import oscar.OscarProperties;

public final class Page_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/struts-logic.tld", Long.valueOf(1780193738112L));
    _jspx_dependants.put("/WEB-INF/struts-html.tld", Long.valueOf(1780193738112L));
    _jspx_dependants.put("/WEB-INF/struts-bean.tld", Long.valueOf(1780193738112L));
    _jspx_dependants.put("/WEB-INF/security.tld", Long.valueOf(1780193738112L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("oscar.oscarLab.ca.on");
    _jspx_imports_packages.add("oscar.oscarMDS.data");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(15);
    _jspx_imports_classes.add("oscar.OscarProperties");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("org.oscarehr.util.SpringUtils");
    _jspx_imports_classes.add("org.apache.logging.log4j.Logger");
    _jspx_imports_classes.add("org.apache.commons.collections.MultiHashMap");
    _jspx_imports_classes.add("org.oscarehr.util.MiscUtils");
    _jspx_imports_classes.add("org.oscarehr.common.hl7.v2.oscar_to_oscar.OscarToOscarUtils");
    _jspx_imports_classes.add("org.oscarehr.common.dao.OscarLogDao");
    _jspx_imports_classes.add("oscar.util.StringUtils");
    _jspx_imports_classes.add("oscar.util.UtilDateUtilities");
    _jspx_imports_classes.add("org.apache.commons.lang.StringEscapeUtils");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.release();
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n");
 // Page.jsp is a fragment referenced in index.jsp

      String roleName$ = (String)session.getAttribute("userrole") + "," + (String) session.getAttribute("user");
	  boolean authed=true;

      out.write('\n');
      //  security:oscarSec
      oscar.login.tld.SecurityTag _jspx_th_security_005foscarSec_005f0 = (oscar.login.tld.SecurityTag) _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.get(oscar.login.tld.SecurityTag.class);
      _jspx_th_security_005foscarSec_005f0.setPageContext(_jspx_page_context);
      _jspx_th_security_005foscarSec_005f0.setParent(null);
      // /oscarMDS/Page.jsp(38,0) name = roleName type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setRoleName(roleName$);
      // /oscarMDS/Page.jsp(38,0) name = objectName type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setObjectName("_lab");
      // /oscarMDS/Page.jsp(38,0) name = rights type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setRights("r");
      // /oscarMDS/Page.jsp(38,0) name = reverse type = boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_security_005foscarSec_005f0.setReverse(true);
      int _jspx_eval_security_005foscarSec_005f0 = _jspx_th_security_005foscarSec_005f0.doStartTag();
      if (_jspx_eval_security_005foscarSec_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write('\n');
        out.write('	');
authed=false; 
        out.write('\n');
        out.write('	');
response.sendRedirect("../securityError.jsp?type=_lab");
        out.write('\n');
      }
      if (_jspx_th_security_005foscarSec_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      _005fjspx_005ftagPool_005fsecurity_005foscarSec_0026_005froleName_005frights_005freverse_005fobjectName.reuse(_jspx_th_security_005foscarSec_005f0);
      out.write('\n');

if(!authed) {
	return;
}

      out.write('\n');
      out.write('\n');

Logger logger=MiscUtils.getLogger();

oscar.OscarProperties props = oscar.OscarProperties.getInstance();
String rapid_review = (props.getProperty("RAPID_REVIEW","")).trim();
String view = (String)request.getAttribute("view");
Integer pageSize=(Integer)request.getAttribute("pageSize");
Integer pageNum=(Integer)request.getAttribute("pageNum");
Integer pageCount=(Integer)request.getAttribute("pageCount");
Map<String,String> docType=(Map<String,String>)request.getAttribute("docType");
Map<String,List<String>> patientDocs=(Map<String,List<String>>)request.getAttribute("patientDocs");
String providerNo=(String)request.getAttribute("providerNo");
String searchProviderNo=(String)request.getAttribute("searchProviderNo");
Map<String,String> patientIdNames=(Map<String,String>)request.getAttribute("patientIdNames");
String patientIdNamesStr=(String)request.getAttribute("patientIdNamesStr");
Map<String,String> docStatus=(Map<String,String>)request.getAttribute("docStatus");
String patientIdStr =(String)request.getAttribute("patientIdStr");
Map<String,List<String>> typeDocLab =(Map<String,List<String>>)request.getAttribute("typeDocLab");
String demographicNo=(String)request.getAttribute("demographicNo");
String ackStatus = (String)request.getAttribute("ackStatus");
List labdocs=(List)request.getAttribute("labdocs");
Map<String,Integer> patientNumDoc=(Map<String,Integer>)request.getAttribute("patientNumDoc");
Integer totalDocs=(Integer) request.getAttribute("totalDocs");
Integer totalHL7=(Integer)request.getAttribute("totalHL7");
List<String> normals=(List<String>)request.getAttribute("normals");
List<String> abnormals=(List<String>)request.getAttribute("abnormals");
Integer totalNumDocs=(Integer)request.getAttribute("totalNumDocs");
String selectedCategory = request.getParameter("selectedCategory");
String selectedCategoryPatient = request.getParameter("selectedCategoryPatient");
String selectedCategoryType = request.getParameter("selectedCategoryType");
boolean isListView = Boolean.valueOf(request.getParameter("isListView"));

OscarLogDao oscarLogDao = (OscarLogDao) SpringUtils.getBean("oscarLogDao");
String curUser_no = (String) session.getAttribute("user");


      out.write('\n');
      out.write('\n');
 if (isListView && pageNum == 0) { 
      out.write("\n		<script type=\"text/javascript\">\n			function submitLabel(lblval){\n		       	 document.forms['TDISLabelForm'].label.value = document.forms['acknowledgeForm'].label.value;\n	       	}\n            if (!DataTable.isDataTable('#summaryView')) {\n                oTable=jQuery('#summaryView').DataTable({\n                    \"bPaginate\": false,\n                    \"dom\": \"lrtip\",\n                    \"order\": [],\n                    \"language\": {\n                                \"url\": \"");
      out.print(request.getContextPath() );
      out.write("/library/DataTables/i18n/");
      if (_jspx_meth_bean_005fmessage_005f0(_jspx_page_context))
        return;
      out.write(".json\"\n                            }\n                });\n                jQuery('#myFilterTextField').keyup(function(){\n                    oTable.search(jQuery(this).val()).draw();\n                });\n            }\n\n		</script>\n\n        <table id=\"scrollNumber1\" style=\"width:100%\">\n            <tr>\n                <td class=\"subheader\" colspan=\"10\" style=\"text-align:left\">\n\n                               ");
 if (labdocs.size() > 0) { 
      out.write("\n                                   <input id=\"topFBtn\" type=\"button\" class=\"btn\" value=\"");
      if (_jspx_meth_bean_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("\" onClick=\"parent.checkSelected(document)\">\n                                   ");
 if (ackStatus.equals("N") || ackStatus.isEmpty()) {
      out.write("\n                                       <input id=\"topFileBtn\" type=\"button\" class=\"btn\" value=\"");
      if (_jspx_meth_bean_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("\" onclick=\"parent.submitFile(document)\"/>\n                                   ");
 }
                                    
      out.write("\n                                       &nbsp; ");
      if (_jspx_meth_bean_005fmessage_005f3(_jspx_page_context))
        return;
      out.write(": <input type=\"checkbox\" id=\"ack_next_chk\" onclick=\"toggleRapidReview();\" ");
      out.print(rapid_review);
      out.write(">\n&nbsp; ");
      if (_jspx_meth_bean_005fmessage_005f4(_jspx_page_context))
        return;
      out.write(": <input type=\"checkbox\" id=\"showAck\" onclick='toggleReviewed()'>\n                                    ");

                               }
      out.write("<span style=\"float:right;\">\n                               <label>");
      if (_jspx_meth_bean_005fmessage_005f5(_jspx_page_context))
        return;
      out.write(": <input type=\"text\" style=\"height:20px;\" id=\"myFilterTextField\"></label></span>\n                               <input type=\"hidden\" id=\"currentNumberOfPages\" value=\"0\">\n                  </td>\n            </tr>\n            <tr>\n                <td style=\"margin:0px;padding:0px;\">\n					<div id=\"listViewDocs\" style=\"max-height:850px; overflow-y:scroll;\" onscroll=\"handleScroll(this)\">\n\n					<table id=\"summaryView\" class=\"table-striped table-hover\" style=\"width:100%; margin:0px; padding:0px;\">\n					<thead>\n						<tr>\n                            <th class=\"header-cell\">\n                                <input type=\"checkbox\" onclick=\"checkAllLabs('lab_form');\" name=\"checkA\" >\n                                ");
      if (_jspx_meth_bean_005fmessage_005f6(_jspx_page_context))
        return;
      out.write("\n                            </th>\n                            <th class=\"header-cell\">\n                                ");
      if (_jspx_meth_bean_005fmessage_005f7(_jspx_page_context))
        return;
      out.write("\n                            </th>\n                            <th class=\"header-cell\">\n                                ");
      if (_jspx_meth_bean_005fmessage_005f8(_jspx_page_context))
        return;
      out.write("\n                            </th>\n                            <th class=\"header-cell\">\n                                ");
      if (_jspx_meth_bean_005fmessage_005f9(_jspx_page_context))
        return;
      out.write("\n                            </th>\n                            <th class=\"header-cell\">\n                                ");
      if (_jspx_meth_bean_005fmessage_005f10(_jspx_page_context))
        return;
      out.write("\n                            </th>\n                            <th class=\"header-cell\">\n                                ");
      if (_jspx_meth_bean_005fmessage_005f11(_jspx_page_context))
        return;
      out.write("\n                            </th>\n                            <th class=\"header-cell\">\n                                ");
      if (_jspx_meth_bean_005fmessage_005f12(_jspx_page_context))
        return;
      out.write("\n                            </th>\n                            <th class=\"header-cell\">\n                                ");
      if (_jspx_meth_bean_005fmessage_005f13(_jspx_page_context))
        return;
      out.write("\n                            </th>\n                            <th class=\"header-cell\">\n                                ");
      if (_jspx_meth_bean_005fmessage_005f14(_jspx_page_context))
        return;
      out.write("\n                            </th>\n                            <th class=\"header-cell\">\n                                Ack #\n                            </th>\n                        </tr>\n                          </thead>\n                          <!--<tbody>-->\n                                            ");

							} // End if(pageNum == 1)
                            List<String> doclabid_seq=new ArrayList<String>();
                            Integer number_of_rows_per_page=pageSize;
                            Integer totalNoPages=pageCount;
                            Integer total_row_index=labdocs.size()-1;
                            if (total_row_index < 0 || (totalNoPages != null && totalNoPages.intValue() == (pageNum+1))) {
                                	
      out.write(" <input type=\"hidden\" name=\"NoMoreItems\" value=\"true\" /> ");

                            		if (isListView) { 
      out.write("\n		                                <!--<tr>\n		                                    <td colspan=\"9\" style=\"text-align:center\">\n		                                        <i>	");
 if (pageNum == 1 && totalNoPages != null) { 
      out.write("\n		                                        	");
      if (_jspx_meth_bean_005fmessage_005f15(_jspx_page_context))
        return;
      out.write("\n		                                        	");
 } else { 
      out.write("\n		                                        	");
      if (_jspx_meth_bean_005fmessage_005f16(_jspx_page_context))
        return;
      out.write("\n		                                        	");
 } 
      out.write("\n		                                        </i>\n\n		                                    </td>\n		                                </tr>-->\n	                         	");
	}
                            		else {
                            		
      out.write("\n\n                            			<div style=\"text-align:center\">\n                            			");
 if (pageNum < 1) { 
      out.write("\n                                       	");
      if (_jspx_meth_bean_005fmessage_005f17(_jspx_page_context))
        return;
      out.write("\n                                       	");
 } else { 
      out.write("\n                                       	");
      if (_jspx_meth_bean_005fmessage_005f18(_jspx_page_context))
        return;
      out.write("\n                                       	");
 } 
      out.write("\n                            			</div>\n\n                            		");

                            		}

                                }
                            for (int i = 0; i < labdocs.size(); i++) {

                                LabResultData   result =  (LabResultData) labdocs.get(i);

                                String segmentID        =  result.getSegmentID();
                                String status           =  result.getAcknowledgedStatus();

								String labRead = "";
                                Boolean newLab = false;

                                if(result.isHRM() && !oscarLogDao.hasRead(curUser_no,"hrm",segmentID)){
                                    newLab = true;
                                	labRead = "<i class='icon-asterisk' style='font-size: 8px; color:gray; padding-right: 4px;'></i>"; // font-awesome
                                }

                                if( !result.isHRM() && result.isDocument() && !oscarLogDao.hasRead(curUser_no,"document",segmentID)){
                                    newLab = true;
                                    labRead = "<i class='icon-asterisk' style='font-size: 8px; color:gray; padding-right: 4px;'></i>";
                                }

                                if(!result.isHRM() && !result.isDocument() && !oscarLogDao.hasRead(curUser_no,"lab",segmentID)){
                                    newLab = true;
                                	labRead = "<i class='icon-asterisk' style='font-size: 8px; color:gray; padding-right: 4px;'></i>";
                                }


                                String discipline=result.getDiscipline();
                                if(discipline==null || discipline.equalsIgnoreCase("null"))
                                    discipline="";
                                MiscUtils.getLogger().debug("result.isAbnormal()="+result.isAbnormal());
                                doclabid_seq.add(segmentID);
                                request.setAttribute("segmentID", segmentID);
                                String demoName = StringEscapeUtils.escapeJavaScript(result.getPatientName());

                                if (!isListView) {
                                	try {
                                		if (result.isDocument()) { 
      out.write("\n                                <!-- segment ID ");
      out.print( segmentID );
      out.write("  -->\n                                <!-- demographic name ");
      out.print(StringEscapeUtils.escapeJavaScript(result.getPatientName()) );
      out.write("  -->\n                                <form id=\"frmDocumentDisplay_");
      out.print(segmentID);
      out.write("\">\n                                	<input type=\"hidden\" name=\"segmentID\" value=\"");
      out.print(segmentID);
      out.write("\"/>\n									<input type=\"hidden\" name=\"demoName\" value=\"");
      out.print(demoName);
      out.write("\"/>\n									<input type=\"hidden\" name=\"providerNo\" value=\"");
      out.print(providerNo);
      out.write("\"/>\n									<input type=\"hidden\" name=\"searchProviderNo\" value=\"");
      out.print(searchProviderNo);
      out.write("\"/>\n									<input type=\"hidden\" name=\"status\" value=\"");
      out.print(status);
      out.write("\"/>\n								</form>\n                                <div id=\"document_");
      out.print(segmentID);
      out.write("\">\n                        			");
      String _jspx_temp0_url = "../dms/showDocument.jsp";
      String _jspx_temp0_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp0_url + ((_jspx_temp0_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("segmentID", _jspx_temp0_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(segmentID), _jspx_temp0_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("demoName", _jspx_temp0_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(demoName), _jspx_temp0_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("providerNo", _jspx_temp0_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(providerNo), _jspx_temp0_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("searchProviderNo", _jspx_temp0_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(searchProviderNo), _jspx_temp0_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("status", _jspx_temp0_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(status), _jspx_temp0_requestEncoding), out, true);
      out.write("\n								</div>\n                        		");

                                		}
                                		else if (result.isHRM()) {

                                			StringBuilder duplicateLabIds=new StringBuilder();
                                        	for (Integer duplicateLabId : result.getDuplicateLabIds())
                                        	{
                                        		if (duplicateLabIds.length()>0) duplicateLabIds.append(',');
                                        		duplicateLabIds.append(duplicateLabId);
                                        	}
                                		
      out.write("\n\n                                	");
      String _jspx_temp1_url = "../hospitalReportManager/Display.do";
      String _jspx_temp1_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp1_url + ((_jspx_temp1_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("id", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(segmentID ), _jspx_temp1_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("segmentID", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(segmentID ), _jspx_temp1_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("providerNo", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(providerNo ), _jspx_temp1_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("searchProviderNo", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(searchProviderNo ), _jspx_temp1_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("status", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(status ), _jspx_temp1_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("demoName", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(result.getPatientName() ), _jspx_temp1_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("duplicateLabIds", _jspx_temp1_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(duplicateLabIds.toString() ), _jspx_temp1_requestEncoding), out, true);
      out.write("\n		                        		");
 } else {

		                        		
      out.write("\n		                        		");
      out.write("\n		                        		");
      String _jspx_temp2_url = "../lab/CA/ALL/labDisplayAjax.jsp";
      String _jspx_temp2_requestEncoding = request.getCharacterEncoding();
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, _jspx_temp2_url + ((_jspx_temp2_url).indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("segmentID", _jspx_temp2_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(segmentID), _jspx_temp2_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("demoName", _jspx_temp2_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(demoName), _jspx_temp2_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("providerNo", _jspx_temp2_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(providerNo), _jspx_temp2_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("searchProviderNo", _jspx_temp2_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(searchProviderNo), _jspx_temp2_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("status", _jspx_temp2_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode(String.valueOf(status), _jspx_temp2_requestEncoding) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("showLatest", _jspx_temp2_requestEncoding)+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("true", _jspx_temp2_requestEncoding), out, true);
      out.write("\n\n		                        		");

		                        		}
                                	}
                                	catch (Exception e) { logger.error(e.toString()); }
                                }
                                else {
                        		
      out.write("\n                                <tr id=\"labdoc_");
      out.print(segmentID);
      out.write('"');
      out.write(' ');
if(result.isDocument()){
      out.write(" name=\"scannedDoc\" ");
} else{
      out.write(" name=\"HL7lab\" ");
}
      out.write(" class=\"");
      out.print( (result.isAbnormal() ? "AbnormalRes error" : "NormalRes" ) + " " + (result.isMatchedToPatient() ? "AssignedRes" : "UnassignedRes") );
      out.write("\">\n                                <td style=\"width:130px; white-space:nowrap;\">\n                                    <input type=\"checkbox\" name=\"flaggedLabs\" value=\"");
      out.print(segmentID);
      out.write("\">\n                                    <input type=\"hidden\" name=\"labType");
      out.print(segmentID+result.labType);
      out.write("\" value=\"");
      out.print(result.labType);
      out.write("\"/>\n                                    <input type=\"hidden\" name=\"ackStatus\" value=\"");
      out.print( result.isMatchedToPatient() );
      out.write("\" />\n                                    <input type=\"hidden\" name=\"patientName\" value=\"");
      out.print(StringEscapeUtils.escapeHtml(result.patientName) );
      out.write("\"/>\n                                    ");
      out.print(result.getHealthNumber() );
      out.write("\n                                </td>\n                                <td style=\"white-space:nowrap;\">\n                                    ");
 if ( result.isMDS() ){ 
      out.write("\n                                    ");
      out.print(labRead);
      out.write("<a id=\"a");
      out.print(segmentID);
      out.write("\" href=\"javascript:void(0)\"  onclick=\"parent.reportWindow('SegmentDisplay.jsp?segmentID=");
      out.print(segmentID);
      out.write("&providerNo=");
      out.print(providerNo);
      out.write("&searchProviderNo=");
      out.print(searchProviderNo);
      out.write("&status=");
      out.print(status);
      out.write("'); if(this.previousElementSibling) this.previousElementSibling.outerHTML='';\">");
      out.print( StringEscapeUtils.escapeHtml(result.getPatientName()));
      out.write("</a>\n                                    ");
 }else if (result.isCML()){ 
      out.write("\n                                    ");
      out.print(labRead);
      out.write("<a id=\"a");
      out.print(segmentID);
      out.write("\" href=\"javascript:void(0)\"  onclick=\"parent.reportWindow('");
      out.print(request.getContextPath());
      out.write("/lab/CA/ON/CMLDisplay.jsp?segmentID=");
      out.print(segmentID);
      out.write("&providerNo=");
      out.print(providerNo);
      out.write("&searchProviderNo=");
      out.print(searchProviderNo);
      out.write("&status=");
      out.print(status);
      out.write("'); if(this.previousElementSibling) this.previousElementSibling.outerHTML='';\">");
      out.print(StringEscapeUtils.escapeHtml(result.getPatientName()));
      out.write("</a>\n                                    ");
 }else if (result.isHL7TEXT())
                                   	{
                                    	String categoryType=result.getDiscipline();

                                    	if ("REF_I12".equals(categoryType))
                                    	{
	                                    	
      out.write("\n                                      			");
      out.print(labRead);
      out.write("<a id=\"a");
      out.print(segmentID);
      out.write("\" href=\"javascript:void(0)\"  onclick=\"parent.popupConsultation('");
      out.print(segmentID);
      out.write("'); if(this.previousElementSibling) this.previousElementSibling.outerHTML='';\">");
      out.print(StringEscapeUtils.escapeHtml(result.getPatientName()));
      out.write("</a>\n                                    		");

                                    	}
                                    	else if (categoryType!=null && categoryType.startsWith("ORU_R01:"))
                                    	{
	                                    	
      out.write("\n                                      			");
      out.print(labRead);
      out.write("<a id=\"a");
      out.print(segmentID);
      out.write("\" href=\"javascript:void(0)\" onclick=\"parent.reportWindow('");
      out.print(request.getContextPath());
      out.write("/lab/CA/ALL/viewOruR01.jsp?segmentId=");
      out.print(segmentID);
      out.write(")'; if(this.previousElementSibling) this.previousElementSibling.outerHTML='';\">");
      out.print(StringEscapeUtils.escapeHtml(result.getPatientName()));
      out.write("</a>\n                                    		");

                                    	}
                                    	else
                                    	{
	                                    	
      out.write("\n	                                    		");
      out.print(labRead);
      out.write("<a id=\"a");
      out.print(segmentID);
      out.write("\" href=\"javascript:void(0)\"  onclick=\"parent.reportWindow('");
      out.print(request.getContextPath());
      out.write("/lab/CA/ALL/labDisplay.jsp?segmentID=");
      out.print(segmentID);
      out.write("&providerNo=");
      out.print(providerNo);
      out.write("&searchProviderNo=");
      out.print(searchProviderNo);
      out.write("&status=");
      out.print(status);
      out.write("&showLatest=true'); if(this.previousElementSibling) this.previousElementSibling.outerHTML='';\">");
      out.print(StringEscapeUtils.escapeHtml(result.getPatientName()));
      out.write("</a>\n	                                    	");

                                    	}
                                    }
                                    else if (result.isDocument()){
                                	String patientName = result.getPatientName();
                                    	StringBuilder url = new StringBuilder(request.getContextPath());
                                    	url.append("/dms/showDocument.jsp?inWindow=true&segmentID=");
                                    	url.append(segmentID);
                                    	url.append("&providerNo=");
                                    	url.append(providerNo);
                                    	url.append("&searchProviderNo=");
                                    	url.append(searchProviderNo);
                                    	url.append("&status=");
                                    	url.append(status);
                                    	url.append("&demoName=");

                                    	//the browser html parser does not understand javascript so we need to account for the opening
                                    	//and closing quotes used in the onclick event handler
                                    	patientName = StringEscapeUtils.escapeHtml(patientName);

                                    	//now that the html parser will pass the correct characters to the javascript engine we need to
                                    	//escape chars for javascript that are not transformed by the html escape.
                                    	url.append(StringEscapeUtils.escapeJavaScript(patientName));
                                    
      out.write("\n\n                                    ");
      out.print(labRead);
      out.write("<a id=\"a");
      out.print(segmentID);
      out.write("\" href=\"javascript:void(0)\" onclick=\"javascript:parent.reportWindow('");
      out.print(url.toString());
      out.write("'); if(this.previousElementSibling) this.previousElementSibling.outerHTML=''\" >");
      out.print(StringEscapeUtils.escapeHtml(result.getPatientName()));
      out.write("</a>\n\n                                    ");
 }else if(result.isHRM()){
                                    	StringBuilder duplicateLabIds=new StringBuilder();
                                    	for (Integer duplicateLabId : result.getDuplicateLabIds())
                                    	{
                                    		if (duplicateLabIds.length()>0) duplicateLabIds.append(',');
                                    		duplicateLabIds.append(duplicateLabId);
                                    	}
                                    
      out.write("\n                                    ");
      out.print(labRead);
      out.write("<a id=\"a");
      out.print(segmentID);
      out.write("\" href=\"javascript:void(0)\" onclick=\"parent.reportWindow('");
      out.print(request.getContextPath());
      out.write("/hospitalReportManager/Display.do?id=");
      out.print(segmentID);
      out.write("&segmentID=");
      out.print(segmentID);
      out.write("&providerNo=");
      out.print(providerNo);
      out.write("&searchProviderNo=");
      out.print(searchProviderNo);
      out.write("&status=");
      out.print(status);
      out.write("&demoName=");
      out.print(StringEscapeUtils.escapeHtml(demoName));
      out.write("&duplicateLabIds=");
      out.print(duplicateLabIds.toString());
      out.write(" '); if(this.previousElementSibling) this.previousElementSibling.outerHTML='';\">");
      out.print(result.getPatientName());
      out.write("</a>\n                                    ");
 }else {
      out.write("\n                                    ");
      out.print(labRead);
      out.write("<a id=\"a");
      out.print(segmentID);
      out.write("\" href=\"javascript:void(0)\" onclick=\"parent.reportWindow('");
      out.print(request.getContextPath());
      out.write("/lab/CA/BC/labDisplay.jsp?segmentID=");
      out.print(segmentID);
      out.write("&providerNo=");
      out.print(providerNo);
      out.write("&searchProviderNo=");
      out.print(searchProviderNo);
      out.write("&status=");
      out.print(status);
      out.write("'); if(this.previousElementSibling) this.previousElementSibling.outerHTML='';\">");
      out.print(StringEscapeUtils.escapeJavaScript(result.getPatientName()));
      out.write("</a>\n                                    ");
 }
      out.write("\n                                </td>\n                                <td style=\"white-space:nowrap;\">\n                                    ");
      out.print(result.getSex() );
      out.write("\n                                </td>\n                                <td style=\"white-space:nowrap;\">\n                                    ");

                                    if(newLab) {
                                    
      out.write("\n                                    ");
      if (_jspx_meth_bean_005fmessage_005f19(_jspx_page_context))
        return;
      out.write("&nbsp;\n                                    ");

                                    }
                                    if (result.isAbnormal()) {
                                    
      out.write("\n                                    ");
      if (_jspx_meth_bean_005fmessage_005f20(_jspx_page_context))
        return;
      out.write("\n                                    ");
 } 
      out.write("\n                                </td>\n                                <td style=\"white-space:nowrap;\">\n                                    ");
      out.print(result.getDateTime() + (result.isDocument() ? " / " + result.lastUpdateDate : ""));
      out.write("\n                                </td>\n                                <td style=\"white-space:nowrap;\">\n                                    ");
      out.print(result.getPriority());
      out.write("\n                                </td>\n                                <td style=\"white-space:nowrap;\">\n                                    ");
      out.print((result.getRequestingClient() == "null" ? "" : result.getRequestingClient()));
      out.write("\n                                </td>\n                                <td style=\"white-space:nowrap;\">\n                                    ");
      out.print(result.isDocument() ? result.description == null ? "" : result.description : result.getDisciplineDisplayString());
      out.write("\n                                </td>\n                                <td style=\"white-space:nowrap;\"> <!--  -->\n                                    ");
      out.print( ((result.isReportCancelled())? "Cancelled" : result.isFinal() ? "Final" : "Partial"));
      out.write("\n                                </td>\n                                <td style=\"white-space:nowrap;\">\n                                    ");
 int multiLabCount = result.getMultipleAckCount(); 
      out.write("\n                                    ");
      out.print( result.getAckCount() );
      out.write("&#160");
 if ( multiLabCount >= 0 ) { 
      out.write('(');
      out.print( result.getMultipleAckCount() );
      out.write(')');
}
      out.write("\n                                </td>\n                            </tr>\n                         ");
 }


                            } // End else from if(isListView)
                            if (isListView && pageNum == 0) { 
      out.write("\n                            </tbody>\n                       	</table>\n\n                       	<table style=\"margin:0px;padding:0px; width: 100%;\" >\n                       		<tr><td>\n                       			<div id='loader' style=\"display:none\"><img src='");
      out.print(request.getContextPath());
      out.write("/images/DMSLoader.gif'> ");
      if (_jspx_meth_bean_005fmessage_005f21(_jspx_page_context))
        return;
      out.write("</div>\n                       		</td></tr>\n                       	</table>\n                       	</div>\n                       	");
 if (labdocs.size() > 0) { 
      out.write("\n                       	<table width=\"100%\" style=\"margin:0px;padding:0px;\" cellpadding=\"0\" cellspacing=\"0\">\n                            <tr class=\"MainTableBottomRow\">\n                                <td class=\"subheader\"  colspan=\"10\" style=\"text-align:left;\">\n                                    <table style=\"width: 100%;\">\n                                        <tr>\n                                            <td style=\"width: 30%; text-align:left; vertical-align:middle;\">\n\n                                                    <input type=\"button\" class=\"btn\" value=\"");
      if (_jspx_meth_bean_005fmessage_005f22(_jspx_page_context))
        return;
      out.write("\" onClick=\"parent.checkSelected(document)\">\n                                                    ");
 if (ackStatus.equals("N")) {
      out.write("\n                                                        <input type=\"button\" class=\"btn\" value=\"");
      if (_jspx_meth_bean_005fmessage_005f23(_jspx_page_context))
        return;
      out.write("\" onclick=\"parent.submitFile(document)\"/>\n                                                    ");
 }  
      out.write("\n                                            </td>\n                                        <script type=\"text/javascript\">\n                                                var doclabid_seq='");
      out.print(doclabid_seq);
      out.write("';\n                                                doclabid_seq=doclabid_seq.replace('[','');\n                                                doclabid_seq=doclabid_seq.replace(']','');\n                                                var arr=doclabid_seq.split(',');\n                                                var arr2=new Array();\n                                                for(var i=0;i<arr.length;i++){\n                                                    var ele=arr[i];\n                                                    ele=ele.replace(' ','');\n                                                    arr2.push(ele);\n                                                }\n                                                doclabid_seq=arr2;\n\n                                                oldestLab = '");
      out.print(request.getAttribute("oldestLab") );
      out.write("';\n\n	                                            for( var i = 0; i < localStorage.length; i++ ) {\n		                                            var key = localStorage.key(i);\n	                                            	if( key == \"rapidreview\" && typeof document.getElementById('ack_next_chk') !== 'undefined'){\n                                                        console.log(\"rapid review checkbox set to \"+localStorage.getItem(key));\n                                                        if (localStorage.getItem(key) == \"true\" ){\n                                            			    document.getElementById('ack_next_chk').checked = true;\n                                                        }\n                                                    }\n		                                        }\n\n                                                function toggleRapidReview() {\n                                                    localStorage.setItem(\"rapidreview\",document.getElementById('ack_next_chk').checked);\n\n                                                }\n");
      out.write("                                        </script>\n                                        </tr>\n                                    </table>\n                                </td>\n                            </tr>\n                    </table>\n                    ");
 } 
      out.write("\n                </td>\n            </tr>\n        </table>\n\n    ");
 } // End if (pageNum == 1) 
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_bean_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f0 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f0.setParent(null);
    // /oscarMDS/Page.jsp(96,95) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f0.setKey("global.i18nLanguagecode");
    int _jspx_eval_bean_005fmessage_005f0 = _jspx_th_bean_005fmessage_005f0.doStartTag();
    if (_jspx_th_bean_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f1 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f1.setParent(null);
    // /oscarMDS/Page.jsp(111,88) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f1.setKey("oscarMDS.index.btnForward");
    int _jspx_eval_bean_005fmessage_005f1 = _jspx_th_bean_005fmessage_005f1.doStartTag();
    if (_jspx_th_bean_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f2 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f2.setParent(null);
    // /oscarMDS/Page.jsp(113,95) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f2.setKey("global.File");
    int _jspx_eval_bean_005fmessage_005f2 = _jspx_th_bean_005fmessage_005f2.doStartTag();
    if (_jspx_th_bean_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f3 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f3.setParent(null);
    // /oscarMDS/Page.jsp(116,46) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f3.setKey("oscarMDS.index.RapidReview");
    int _jspx_eval_bean_005fmessage_005f3 = _jspx_th_bean_005fmessage_005f3.doStartTag();
    if (_jspx_th_bean_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f3);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f4 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f4.setParent(null);
    // /oscarMDS/Page.jsp(117,7) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f4.setKey("oscarMDS.search.formReportStatusAcknowledged");
    int _jspx_eval_bean_005fmessage_005f4 = _jspx_th_bean_005fmessage_005f4.doStartTag();
    if (_jspx_th_bean_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f4);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f5 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f5.setParent(null);
    // /oscarMDS/Page.jsp(120,38) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f5.setKey("oscarMDS.index.btnSearch");
    int _jspx_eval_bean_005fmessage_005f5 = _jspx_th_bean_005fmessage_005f5.doStartTag();
    if (_jspx_th_bean_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f5);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f6 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f6.setParent(null);
    // /oscarMDS/Page.jsp(133,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f6.setKey("oscarMDS.index.msgHealthNumber");
    int _jspx_eval_bean_005fmessage_005f6 = _jspx_th_bean_005fmessage_005f6.doStartTag();
    if (_jspx_th_bean_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f6);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f7 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f7.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f7.setParent(null);
    // /oscarMDS/Page.jsp(136,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f7.setKey("oscarMDS.index.msgPatientName");
    int _jspx_eval_bean_005fmessage_005f7 = _jspx_th_bean_005fmessage_005f7.doStartTag();
    if (_jspx_th_bean_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f7);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f8 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f8.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f8.setParent(null);
    // /oscarMDS/Page.jsp(139,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f8.setKey("oscarMDS.index.msgSex");
    int _jspx_eval_bean_005fmessage_005f8 = _jspx_th_bean_005fmessage_005f8.doStartTag();
    if (_jspx_th_bean_005fmessage_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f8);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f9 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f9.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f9.setParent(null);
    // /oscarMDS/Page.jsp(142,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f9.setKey("oscarMDS.index.msgResultStatus");
    int _jspx_eval_bean_005fmessage_005f9 = _jspx_th_bean_005fmessage_005f9.doStartTag();
    if (_jspx_th_bean_005fmessage_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f9);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f10 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f10.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f10.setParent(null);
    // /oscarMDS/Page.jsp(145,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f10.setKey("oscarMDS.index.msgDateTest");
    int _jspx_eval_bean_005fmessage_005f10 = _jspx_th_bean_005fmessage_005f10.doStartTag();
    if (_jspx_th_bean_005fmessage_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f10);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f11 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f11.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f11.setParent(null);
    // /oscarMDS/Page.jsp(148,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f11.setKey("oscarMDS.index.msgOrderPriority");
    int _jspx_eval_bean_005fmessage_005f11 = _jspx_th_bean_005fmessage_005f11.doStartTag();
    if (_jspx_th_bean_005fmessage_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f11);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f12 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f12.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f12.setParent(null);
    // /oscarMDS/Page.jsp(151,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f12.setKey("oscarMDS.index.msgRequestingClient");
    int _jspx_eval_bean_005fmessage_005f12 = _jspx_th_bean_005fmessage_005f12.doStartTag();
    if (_jspx_th_bean_005fmessage_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f12);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f13(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f13 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f13.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f13.setParent(null);
    // /oscarMDS/Page.jsp(154,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f13.setKey("oscarMDS.index.msgDiscipline");
    int _jspx_eval_bean_005fmessage_005f13 = _jspx_th_bean_005fmessage_005f13.doStartTag();
    if (_jspx_th_bean_005fmessage_005f13.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f13);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f14(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f14 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f14.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f14.setParent(null);
    // /oscarMDS/Page.jsp(157,32) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f14.setKey("oscarMDS.index.msgReportStatus");
    int _jspx_eval_bean_005fmessage_005f14 = _jspx_th_bean_005fmessage_005f14.doStartTag();
    if (_jspx_th_bean_005fmessage_005f14.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f14);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f15(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f15 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f15.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f15.setParent(null);
    // /oscarMDS/Page.jsp(177,43) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f15.setKey("oscarMDS.index.msgNoReports");
    int _jspx_eval_bean_005fmessage_005f15 = _jspx_th_bean_005fmessage_005f15.doStartTag();
    if (_jspx_th_bean_005fmessage_005f15.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f15);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f16(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f16 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f16.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f16.setParent(null);
    // /oscarMDS/Page.jsp(179,43) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f16.setKey("oscarMDS.index.msgNoMoreReports");
    int _jspx_eval_bean_005fmessage_005f16 = _jspx_th_bean_005fmessage_005f16.doStartTag();
    if (_jspx_th_bean_005fmessage_005f16.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f16);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f17(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f17 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f17.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f17.setParent(null);
    // /oscarMDS/Page.jsp(191,40) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f17.setKey("oscarMDS.index.msgNoReports");
    int _jspx_eval_bean_005fmessage_005f17 = _jspx_th_bean_005fmessage_005f17.doStartTag();
    if (_jspx_th_bean_005fmessage_005f17.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f17);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f18(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f18 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f18.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f18.setParent(null);
    // /oscarMDS/Page.jsp(193,40) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f18.setKey("oscarMDS.index.msgNoMoreReports");
    int _jspx_eval_bean_005fmessage_005f18 = _jspx_th_bean_005fmessage_005f18.doStartTag();
    if (_jspx_th_bean_005fmessage_005f18.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f18);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f19(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f19 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f19.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f19.setParent(null);
    // /oscarMDS/Page.jsp(379,36) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f19.setKey("WriteScript.msgRxStatus.New");
    int _jspx_eval_bean_005fmessage_005f19 = _jspx_th_bean_005fmessage_005f19.doStartTag();
    if (_jspx_th_bean_005fmessage_005f19.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f19);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f20(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f20 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f20.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f20.setParent(null);
    // /oscarMDS/Page.jsp(384,36) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f20.setKey("global.Abnormal");
    int _jspx_eval_bean_005fmessage_005f20 = _jspx_th_bean_005fmessage_005f20.doStartTag();
    if (_jspx_th_bean_005fmessage_005f20.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f20);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f21(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f21 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f21.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f21.setParent(null);
    // /oscarMDS/Page.jsp(417,127) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f21.setKey("caseload.msgLoading");
    int _jspx_eval_bean_005fmessage_005f21 = _jspx_th_bean_005fmessage_005f21.doStartTag();
    if (_jspx_th_bean_005fmessage_005f21.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f21);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f22(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f22 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f22.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f22.setParent(null);
    // /oscarMDS/Page.jsp(429,92) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f22.setKey("oscarMDS.index.btnForward");
    int _jspx_eval_bean_005fmessage_005f22 = _jspx_th_bean_005fmessage_005f22.doStartTag();
    if (_jspx_th_bean_005fmessage_005f22.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f22);
    return false;
  }

  private boolean _jspx_meth_bean_005fmessage_005f23(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  bean:message
    org.apache.struts.taglib.bean.MessageTag _jspx_th_bean_005fmessage_005f23 = (org.apache.struts.taglib.bean.MessageTag) _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.get(org.apache.struts.taglib.bean.MessageTag.class);
    _jspx_th_bean_005fmessage_005f23.setPageContext(_jspx_page_context);
    _jspx_th_bean_005fmessage_005f23.setParent(null);
    // /oscarMDS/Page.jsp(431,96) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_bean_005fmessage_005f23.setKey("global.File");
    int _jspx_eval_bean_005fmessage_005f23 = _jspx_th_bean_005fmessage_005f23.doStartTag();
    if (_jspx_th_bean_005fmessage_005f23.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fbean_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_bean_005fmessage_005f23);
    return false;
  }
}
