/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2026-06-03 23:02:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.demographic;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import oscar.OscarProperties;
import org.oscarehr.util.SpringUtils;
import org.oscarehr.common.dao.UserPropertyDAO;
import org.oscarehr.common.model.UserProperty;

public final class demographiceditdemographic_js_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(6);
    _jspx_imports_classes.add("oscar.OscarProperties");
    _jspx_imports_classes.add("org.oscarehr.util.SpringUtils");
    _jspx_imports_classes.add("org.oscarehr.common.dao.UserPropertyDAO");
    _jspx_imports_classes.add("org.oscarehr.common.model.UserProperty");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n\n\n\n\n\n");

	String curUser_no = (String) session.getAttribute("user");
	UserPropertyDAO userPropertyDao = SpringUtils.getBean(UserPropertyDAO.class); 
	UserProperty tabViewProp = userPropertyDao.getProp(curUser_no, UserProperty.OPEN_IN_TABS);
    boolean openInTabs = false;
    if ( tabViewProp == null ) {
        openInTabs = oscar.OscarProperties.getInstance().getBooleanProperty("open_in_tabs", "true");
    } else {
        openInTabs = oscar.OscarProperties.getInstance().getBooleanProperty("open_in_tabs", "true") || Boolean.parseBoolean(tabViewProp.getValue());
    }

      out.write("\n\nctx = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n\nfunction rs(n,u,w,h,x) {\n  args=\"width=\"+w+\",height=\"+h+\",resizable=yes,scrollbars=yes,status=0,top=360,left=30\";\n  remote=window.open(u,n,args);\n  if (remote != null) {\n    if (remote.opener == null)\n      remote.opener = self;\n  }\n  if (x == 1) { return remote; }\n}\n\nvar awnd=null;\nfunction ScriptAttach() {\n  awnd=rs('swipe','zdemographicswipe.htm',800,800,1);\n  awnd.focus();\n}\n\nfunction setfocus() {\n  this.focus();\n  document.titlesearch.keyword.focus();\n  document.titlesearch.keyword.select();\n}\nfunction stripSpaces(ctrl) {\n	ctrl.value = ctrl.value.replaceAll(\" \", \"\");\n}\nfunction upCaseCtrl(ctrl) {\n	ctrl.value = ctrl.value.toUpperCase();\n}\nfunction popupPage(vheight, vwidth, varpage, inTabs) { //open a new popup window\n\n  windowprops = \"height=\"+vheight+\",width=\"+vwidth+\",location=no,scrollbars=yes,menubars=no,toolbars=no,resizable=yes,screenX=50,screenY=50,top=20,left=20\";\n\n    inTabs      = typeof(inTabs)     != 'undefined' ? inTabs : ");
      out.print(openInTabs);
      out.write(";\n    var windowName  = 'Master';\n\n	if (varpage == null || varpage == -1) {\n		  	return false;\n	}\n    if( varpage.indexOf(\"..\") == 0 ) {\n            varpage = ctx + varpage.substr(2);\n    }\n\n    if (inTabs) {\n                popup = window.open(varpage, windowName);\n    } else {\n                popup = window.open(varpage, windowName, windowprops);\n    }\n    if (popup != null) {\n        if (popup.opener == null) {\n            popup.opener = self;\n        }\n        popup.focus();\n    }\n}\n\n\nfunction popupOscarRx(vheight,vwidth,varpage, inTabs) { //open a new popup window\n  var page = varpage;\n  windowprops = \"height=\"+vheight+\",width=\"+vwidth+\",location=no,scrollbars=yes,menubars=no,toolbars=no,resizable=yes,screenX=0,screenY=0,top=0,left=0\";\n\n    inTabs      = typeof(inTabs)     != 'undefined' ? inTabs : ");
      out.print(openInTabs);
      out.write(";\n    var windowName  = 'Master';\n\n	if (varpage == null || varpage == -1) {\n		  	return false;\n	}\n    if( varpage.indexOf(\"..\") == 0 ) {\n            varpage = ctx + varpage.substr(2);\n    }\n\n    if (inTabs) {\n                popup = window.open(varpage, windowName);\n    } else {\n                popup = window.open(varpage, windowName, windowprops);\n    }\n    if (popup != null) {\n        if (popup.opener == null) {\n            popup.opener = self;\n        }\n        popup.focus();\n    }\n}\n\n\n\n\nfunction checkRosterStatus() {\n	if (rosterStatusChangedNotBlank()) {\n		if (document.updatedelete.roster_status.value==\"RO\") { //Patient rostered\n			if (!rosterStatusDateValid(false)) return false;\n			if (!rosterEnrolledToValid(false)) return false;\n			if(rosterStatusTerminationDateFilled() || rosterStatusTerminationReasonFilled() ) {\n				alert('Please clear the roster termination date and roster termination reason fields');\n				return false;\n			}\n			return true;\n		} else if(document.updatedelete.roster_status.value==\"TE\") {\n");
      out.write("			if (!rosterStatusDateValid(false)) return false;\n			if (!rosterStatusTerminationDateValid(false)) return false;\n			if (!rosterStatusTerminationReasonNotBlank()) return false;\n			return true;\n		} else {\n			return true;\n		}\n	}\n\n	if (rosterStatusDateAllowed()) {\n		if (document.updatedelete.roster_status.value==\"RO\") { //Patient rostered\n			if (!rosterStatusDateValid(false)) return false;\n			if (!rosterEnrolledToValid(false)) return false;\n		}\n		else {\n			if (!rosterStatusTerminationDateValid(true)) return false;\n		}\n	} else {\n		return false;\n	}\n	\n	if (!rosterStatusDateValid(true)) return false;\n	if (!rosterStatusTerminationDateValid(true)) return false;\n	if (!rosterEnrolledToValid(true)) return false;\n	return true;\n}\n\nfunction rosterStatusChanged() {\n	return (document.updatedelete.initial_rosterstatus.value!=document.updatedelete.roster_status.value);\n}\nfunction checkPatientStatus() {\n	if (patientStatusChanged()) {\n		return patientStatusDateValid(false);\n	}\n	return patientStatusDateValid(true);\n}\n\nfunction patientStatusChanged() {\n");
      out.write("	return (document.updatedelete.initial_patientstatus.value!=document.updatedelete.patient_status.value);\n}\nfunction checkSex() {\n	var sex = document.updatedelete.sex.value;\n	\n	if(sex.length == 0)\n	{\n		alert (\"You must select a Gender.\");\n		return(false);\n	}\n\n	return(true);\n}\n\n\nfunction checkTypeInEdit() {\n  if ( !checkName() ) return false;\n  if ( !checkDob() ) return false;\n  if ( !checkHin() ) return false;\n  if ( !checkSex() ) return false;\n  ");
 if("false".equals(OscarProperties.getInstance().getProperty("skip_postal_code_validation","false"))) { 
      out.write("\n  if ( !isPostalCode() ) return false;\n  ");
 } 
      out.write("\n  if ( !checkRosterStatus() ) return false;\n  if ( !checkPatientStatus() ) return false;\n  return(true);\n}\n\nfunction formatPhoneNum() {\n    if (document.updatedelete.phone.value.length == 10) {\n        document.updatedelete.phone.value = document.updatedelete.phone.value.substring(0,3) + \"-\" + document.updatedelete.phone.value.substring(3,6) + \"-\" + document.updatedelete.phone.value.substring(6);\n        }\n    if (document.updatedelete.phone.value.length == 11 && document.updatedelete.phone.value.charAt(3) == '-') {\n        document.updatedelete.phone.value = document.updatedelete.phone.value.substring(0,3) + \"-\" + document.updatedelete.phone.value.substring(4,7) + \"-\" + document.updatedelete.phone.value.substring(7);\n    }\n    if (document.updatedelete.phone2.value.length == 10) {\n        document.updatedelete.phone2.value = document.updatedelete.phone2.value.substring(0,3) + \"-\" + document.updatedelete.phone2.value.substring(3,6) + \"-\" + document.updatedelete.phone2.value.substring(6);\n        }\n    if (document.updatedelete.phone2.value.length == 11 && document.updatedelete.phone2.value.charAt(3) == '-') {\n");
      out.write("        document.updatedelete.phone2.value = document.updatedelete.phone2.value.substring(0,3) + \"-\" + document.updatedelete.phone2.value.substring(4,7) + \"-\" + document.updatedelete.phone2.value.substring(7);\n    }\n}\n\n//\nfunction rs(n,u,w,h,x) {\n  args=\"width=\"+w+\",height=\"+h+\",resizable=yes,scrollbars=yes,status=0,top=60,left=30\";\n  remote=window.open(u,n,args);\n}\nfunction referralScriptAttach2(elementName, name2) {\n     var d = elementName;\n     t0 = escape(\"document.forms[1].elements[\\'\"+d+\"\\'].value\");\n     t1 = escape(\"document.forms[1].elements[\\'\"+name2+\"\\'].value\");\n     rs('att',('../billing/CA/ON/searchRefDoc.jsp?param='+t0+'&param2='+t1),800,800,1);\n}\nfunction removeAccents(s){\n    var r=s.toLowerCase();\n    r = r.replace(new RegExp(\"\\\\s\", 'g'),\"\");\n    r = r.replace(new RegExp(\"[Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½]\", 'g'),\"a\");\n    r = r.replace(new RegExp(\"Ã¯Â¿Â½\", 'g'),\"ae\");\n    r = r.replace(new RegExp(\"Ã¯Â¿Â½\", 'g'),\"c\");\n    r = r.replace(new RegExp(\"[Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½]\", 'g'),\"e\");\n");
      out.write("    r = r.replace(new RegExp(\"[Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½]\", 'g'),\"i\");\n    r = r.replace(new RegExp(\"Ã¯Â¿Â½\", 'g'),\"n\");\n    r = r.replace(new RegExp(\"[Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½]\", 'g'),\"o\");\n    r = r.replace(new RegExp(\"?\", 'g'),\"oe\");\n    r = r.replace(new RegExp(\"[Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½Ã¯Â¿Â½]\", 'g'),\"u\");\n    r = r.replace(new RegExp(\"[Ã¯Â¿Â½Ã¯Â¿Â½]\", 'g'),\"y\");\n    r = r.replace(new RegExp(\"\\\\W\", 'g'),\"\");\n    return r;\n}\n\nfunction isPostalCode()\n{\n    if(isCanadian()){\n         e = document.updatedelete.postal;\n         postalcode = e.value;\n        	\n         rePC = new RegExp(/(^s*([a-z](\\s)?\\d(\\s)?){3}$)s*/i);\n    \n         if (!rePC.test(postalcode)) {\n              e.focus();\n              alert(\"The entered Postal Code is not valid\");\n              return false;\n         }\n    }//end cdn check\n\nreturn true;\n}\n\nfunction isPostalCode2()\n{\n    if(isCanadian()){\n         e = document.updatedelete.residentialPostal;\n         postalcode = e.value;\n        	\n         rePC = new RegExp(/(^s*([a-z](\\s)?\\d(\\s)?){3}$)s*/i);\n");
      out.write("    \n         if (!rePC.test(postalcode)) {\n              e.focus();\n              alert(\"The entered residential Postal Code is not valid\");\n              return false;\n         }\n    }//end cdn check\n\nreturn true;\n}\n\nfunction isCanadian(){\n	e = document.updatedelete.province;\n    if(e.selectedIndex < 0) { return false; }\n    var province = e.options[e.selectedIndex].value;\n    \n    if ( province.indexOf(\"US\")>-1 || province==\"OT\"){ //if not canadian\n            return false;\n    }\n    return true;\n}\n\n\nfunction setProvince(sdCode) {\n	jQuery(\"#country\").on('change',function(){\n		updateProvinces('');\n	});\n	\n    jQuery.ajax({\n        type: \"POST\",\n        url:  '../demographicSupport.do',\n        data: 'method=getCountryAndProvinceCodes',\n        dataType: 'json',\n        success: function (data) {\n        	jQuery('#country').append(jQuery('<option>').text('').attr('value', ''));\n        	jQuery.each(data, function(i, value) {\n                 jQuery('#country').append(jQuery('<option>').text(value.label).attr('value', value.value));\n");
      out.write("             });\n        	\n        	 if(sdCode.indexOf('-') != -1) {\n            	 jQuery(\"#country\").val(sdCode.split(\"-\")[0]);\n             } else {\n           	//  jQuery(\"#country\").val('CA');\n             }\n        	\n        	updateProvinces(sdCode);\n        }\n	});\n  }\n\n\nfunction updateProvinces(province) {\n	var country = jQuery(\"#country\").val();\n	console.log('country is ' + country );\n	if(country == '') {\n		console.log('t1');\n		return;\n	}\n	\n	jQuery.ajax({\n        type: \"POST\",\n        url:  '../demographicSupport.do',\n        data: 'method=getCountryAndProvinceCodes&country=' + country,\n        dataType: 'json',\n        success: function (data) {\n        	jQuery('#province').empty();\n        	jQuery.each(data, function(i, value) {\n                 jQuery('#province').append(jQuery('<option>').text(value.label).attr('value', value.value));\n             });\n        	\n        	\n        	if(province != null) {\n        		jQuery(\"#province\").val(province);\n        	}\n        	\n        	\n        }\n	});\n}\n\n\nfunction setResidentialProvince(sdCode) {\n");
      out.write("	jQuery(\"#residentialCountry\").on('change',function(){\n		updateResidentialProvinces('');\n	});\n	\n    jQuery.ajax({\n        type: \"POST\",\n        url:  '../demographicSupport.do',\n        data: 'method=getCountryAndProvinceCodes',\n        dataType: 'json',\n        success: function (data) {\n        	jQuery('#residentialCountry').append(jQuery('<option>').text('').attr('value', ''));\n        	jQuery.each(data, function(i, value) {\n                 jQuery('#residentialCountry').append(jQuery('<option>').text(value.label).attr('value', value.value));\n             });\n             \n             if(sdCode.indexOf('-') != -1) {\n            	 jQuery(\"#residentialCountry\").val(sdCode.split(\"-\")[0]);\n             } else {\n           	//  jQuery(\"#residentialCountry\").val('CA');\n             }\n        	\n        	updateResidentialProvinces(sdCode);\n        }\n	});\n  }\n\n\nfunction updateResidentialProvinces(province) {\n	var country = jQuery(\"#residentialCountry\").val();\n	if(country == '') {\n		return;\n	}\n	jQuery.ajax({\n        type: \"POST\",\n");
      out.write("        url:  '../demographicSupport.do',\n        data: 'method=getCountryAndProvinceCodes&country=' + country,\n        dataType: 'json',\n        success: function (data) {\n        	jQuery('#residentialProvince').empty();\n        	 \n        	jQuery.each(data, function(i, value) {\n                 jQuery('#residentialProvince').append(jQuery('<option>').text(value.label).attr('value', value.value));\n             });\n        	\n        	\n        	if(province != null) {\n        		jQuery(\"#residentialProvince\").val(province);\n        	}\n        	\n        	\n        }\n	});\n}");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
