/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.104
 * Generated at: 2026-06-03 22:30:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.casemgmt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class newEncounterLayout_js_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1780193738074L));
    _jspx_dependants.put("jar:file:/home/dmoniz/projects/oscar/catalina_base/webapps/oscar/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153410282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/javascript");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n\n\n\nMessenger.options = {\n		delay: 10,\n		extraClasses: 'messenger-fixed messenger-on-top messenger-on-left',\n		theme: 'future'\n};\n\n// global message\nvar msg;\n\n/*\n * Handles eAAPs notification dismissal\n * \n * @param notificationId ID of the notification to be dismissed\n * \n */\nfunction dismissHandler(notificationId) {\n	jQuery.ajax({\n		type : \"POST\",\n		url : \"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("/notification/create.do\",\n		data : {id: notificationId, type: \"eaaps\"},\n		/*\n		 * success : function(response) { msg.update({ message: \"Notification\n		 * will not be displayed again.\", type: \"success\", actions: false }); },\n		 */\n		error: function(response) {\n			msg.update({\n				message: \"We are sorry, there was an error saving your preference\",\n				type: \"error\",\n				actions: false\n			})\n		}\n	});\n	return msg.hide();\n}\n\n/*\n * Handles messenger display\n * \n * @param url URL of the notification popup\n * @param notificationId Id of the notification\n * @param message Additional message information\n */\nfunction showMessenger(url, notificationId, message) {\n	var messageContent = \"\";\n	// in case URL is specified - make sure it's clickable\n	if (url) {\n		messageContent = \"<a href='javascript:void();' style='color: white' onclick='window.open(\\\"\" + url + \"\\\",\\\"eaaps\\\",\\\"height=700,width=1000,left=10,top=10,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no,status=yes\\\");return false;'  >\"+message+\"</a>\";\n");
      out.write("	} else { // otherwise - just show the message provided\n		messageContent = message;\n	}\n\n	msg = Messenger().post({\n		id: url,\n		singleton: true,\n		type: 'info',\n		message: messageContent,\n		actions: {\n			snooze: {\n				label: 'Snooze',\n				action: function() {\n					return msg.update({\n						message: \"This message will display next time this eChart is open\",\n						type: \"success\",\n						actions: false\n					});\n				}\n			}\n		}\n	});\n}\n\n/*\n * Main entry point into the messenger functionality. This function is called from the eAAP eChart\n * window.\n * \n * @param url URL of the notification popup\n * @param notificationId Id of the notification \n * @param message additional message information to be displayed in the popup\n */\nfunction displayEaapsWindow(url, notificationId, message) {\n	// make sure we give a chance for eChart to load\n	setTimeout(\n		function() {\n			showMessenger(url, notificationId, message);	\n		}, 500\n	);\n}\n\n//////Timer\n        var d = new Date();  //the start\n\n        var totalSeconds = 0;\n        var myVar = setInterval(setTime, 1000);\n");
      out.write("	var toggle = true;\n\n	function toggleATimer(){\n 	    if (toggle) {\n			document.getElementById(\"toggleTimer\").innerHTML=\"&gt;\";\n			clearInterval(myVar);\n			toggle=false;\n		} else {\n			document.getElementById(\"toggleTimer\").innerHTML=\"&#8741;\";\n			myVar = setInterval(setTime, 1000);\n			toggle=true;\n		}\n	}\n	\n	function pasteTimer(){\n            var ed = new Date();\n            $(caseNote).value +=\"\\n\"+document.getElementById(\"startTag\").value+\": \"+d.getHours()+\":\"+pad(d.getMinutes())+\"\\n\"+document.getElementById(\"endTag\").value+\": \"+ed.getHours()+\":\"+pad(ed.getMinutes())+\"\\n\"+pad(parseInt(totalSeconds/3600))+\":\"+pad(parseInt((totalSeconds/60)%60))+\":\"+ pad(totalSeconds%60);\n            adjustCaseNote();\n	}\n\n        function setTime(){\n            ++totalSeconds;\n            if (totalSeconds > 5) {document.getElementById(\"aTimer\").innerHTML =pad(parseInt(totalSeconds/60))+\":\"+ pad(totalSeconds%60);}\n            if (totalSeconds == 1200) {document.getElementById(\"aTimer\").style.backgroundColor= \"#DFF0D8\";} //1200 sec = 20 min light green\n");
      out.write("            if (totalSeconds == 3000) {document.getElementById(\"aTimer\").style.backgroundColor= \"#FDFEC7\";} //3600 sec = 50 min light yellow\n        }\n\n        function pad(val){\n            var valString = val + \"\";\n            if(valString.length < 2)\n            {\n                return \"0\" + valString;\n            } else {\n                return valString;\n            }\n        }\n\n\n\n// add Markdown functions for caseNote editing\n\n    function repeat(string, count) {\n        var result = '';\n        for (var i = 0; i < count; i++) {\n            result += string;\n        }\n        return result;\n    };\n\n    function addTab() {\n        var textarea = $(caseNote);\n        var start = textarea.value.substr(0, textarea.selectionStart);\n        var end = textarea.value.substr(textarea.selectionStart);\n        var tab = \"\\t\";\n        textarea.value = \"\" + start + tab + end;\n        textarea.selectionStart = start.length + tab.length;\n        textarea.selectionEnd = textarea.selectionStart;\n        textarea.focus();\n");
      out.write("    };\n    function shiftTab() {\n        var textarea = $(caseNote);\n        var _a;\n        var start = textarea.value.substr(0, textarea.selectionStart);\n        var end = textarea.value.substr(textarea.selectionStart);\n        if (start[start.length - 1] == '\\t') {\n            start = (_a = start.substr(0, start.length - 1)) !== null && _a !== void 0 ? _a : '';\n        }\n        else if (end[0] == '\\t') {\n            end = end.substr(1);\n        }\n        textarea.value = \"\" + start + end;\n        textarea.selectionStart = start.length;\n        textarea.selectionEnd = textarea.selectionStart;\n        textarea.focus();\n    };\n\n    function addBold() {\n	    var textarea = $(caseNote);\n        var start = textarea.value.substr(0, textarea.selectionStart);\n        var end = textarea.value.substr(textarea.selectionStart);\n        var bold = \"****\";\n        var offset = bold.length - 2;\n        if (textarea.selectionStart != textarea.selectionEnd) {\n            end = textarea.value.substr(textarea.selectionEnd);\n");
      out.write("            var range = textarea.value.slice(textarea.selectionStart, textarea.selectionEnd);\n            bold = \"**\" + range + \"**\";\n            offset = 2;\n        }\n        if (start.length && start[start.length - 1] != '\\n' && start[start.length - 1] != ' ') {\n            bold = \" \" + bold;\n        }\n        if (end.length && end[0] != '\\n' && end[0] != ' ') {\n            bold = bold + \" \";\n            offset += 1;\n        }\n        textarea.value = \"\" + start + bold + end;\n        textarea.selectionStart = start.length + bold.length - offset;\n        textarea.selectionEnd = textarea.selectionStart;\n        textarea.focus();\n\n    }\n\n    function addItalic() {\n	    var textarea = $(caseNote);\n        var start = textarea.value.substr(0, textarea.selectionStart);\n        var end = textarea.value.substr(textarea.selectionStart);\n        var bold = \"**\";\n        var offset = bold.length - 1;\n        if (textarea.selectionStart != textarea.selectionEnd) {\n            end = textarea.value.substr(textarea.selectionEnd);\n");
      out.write("            var range = textarea.value.slice(textarea.selectionStart, textarea.selectionEnd);\n            bold = \"*\" + range + \"*\";\n            offset = 1;\n        }\n        if (start.length && start[start.length - 1] != '\\n' && start[start.length - 1] != ' ') {\n            bold = \" \" + bold;\n        }\n        if (end.length && end[0] != '\\n' && end[0] != ' ') {\n            bold = bold + \" \";\n            offset += 1;\n        }\n        textarea.value = \"\" + start + bold + end;\n        textarea.selectionStart = start.length + bold.length - offset;\n        textarea.selectionEnd = textarea.selectionStart;\n        textarea.focus();\n    };\n\n	\n	 function addLink(type) {\n	    var textarea = $(caseNote);\n        if (type === void 0) { type = 0; }\n        var start = textarea.value.substr(0, textarea.selectionStart);\n        var end = textarea.value.substr(textarea.selectionStart);\n        var link = '';\n        var offset = 0;\n        if (type === 0) {\n            link = '[](http://)';\n            offset = link.length - 1;\n");
      out.write("            if (textarea.selectionStart != textarea.selectionEnd) {\n                end = textarea.value.substr(textarea.selectionEnd);\n                var range = textarea.value.slice(textarea.selectionStart, textarea.selectionEnd);\n                var rangeIsURL = range.match(/https?:\\/\\/(.+)/);\n                link = rangeIsURL ? \"[](\" + range.trim() + \")\" : \"[\" + range.trim() + \"](http://)\";\n                offset = rangeIsURL ? range.trim().length + 3 : 1;\n            }\n        }\n        else {\n            link = '<>';\n            offset = link.length - 1;\n            if (textarea.selectionStart != textarea.selectionEnd) {\n                end = textarea.value.substr(textarea.selectionEnd);\n                var range = textarea.value.slice(textarea.selectionStart, textarea.selectionEnd);\n                link = \"<\" + range + \">\";\n                offset = 1;\n            }\n        }\n        if (start.length && start[start.length - 1] != '\\n' && start[start.length - 1] != ' ') {\n            link = \" \" + link;\n        }\n");
      out.write("        if (end.length && end[0] != '\\n' && end[0] != ' ') {\n            link = link + \" \";\n            offset += 1;\n        }\n        textarea.value = \"\" + start + link + end;\n        textarea.selectionStart = start.length + link.length - offset;\n        textarea.selectionEnd = textarea.selectionStart;\n        textarea.focus();\n    };\n\n    function addHeading (level) {\n	    var textarea = $(caseNote);\n        if (level === void 0) { level = 1; }\n        var start = textarea.value.substr(0, textarea.selectionStart);\n        var end = textarea.value.substr(textarea.selectionStart);\n        var heading = repeat('#', level) + \" \";\n        var offset = 0;\n        if (textarea.selectionStart != textarea.selectionEnd) {\n            end = textarea.value.substr(textarea.selectionEnd);\n            var range = textarea.value.slice(textarea.selectionStart, textarea.selectionEnd);\n            heading = \"\" + heading + range.trim();\n            offset = 0;\n        }\n        if (start.length && start[start.length - 1] != '\\n') {\n");
      out.write("            heading = \"\\n\" + heading;\n        }\n        if (end.length && end[0] != '\\n') {\n            heading = heading + \"\\n\";\n            offset = 1;\n        }\n        textarea.value = \"\" + start + heading + end;\n        textarea.selectionStart = start.length + heading.length - offset;\n        textarea.selectionEnd = textarea.selectionStart;\n        textarea.focus();\n    };\n\n    var handlerOn = 0;\n    function addHandler() {\n        if (handlerOn == 1) { return;}\n        var textarea = $(caseNote);\n        textarea.addEventListener('keydown', function (e) {\n            if (e.key.toLowerCase() === 'enter' && onListing !== null) {\n                e.preventDefault();\n                var start = textarea.value.substr(0, textarea.selectionStart);\n                var end = textarea.value.substr(textarea.selectionStart);\n                var splittedStart = start.split(/\\n/g);\n                var list = '';\n                var pattern = onListing.type === 'unordered' ? /-\\s?/ : /\\d+\\.\\s?/;\n                if (splittedStart.length) {\n");
      out.write("                    var match = splittedStart[splittedStart.length - 1].trim().match(pattern);\n                    if (match && match[0] === match.input) {\n                        splittedStart.pop();\n                        textarea.value = splittedStart.join('\\n') + \"\\n\" + end;\n                        textarea.selectionStart = splittedStart.join('\\n').length + '\\n'.length;\n                        textarea.selectionEnd = textarea.selectionStart;\n                        return onListing = null;\n                    }\n                }\n                if (onListing.type === 'unordered') {\n                    list = \"\\n- \";\n                }\n                if (onListing.type === 'ordered') {\n                    list = \"\\n\" + onListing.number + \". \";\n                    onListing.number++;\n                }\n                textarea.value = \"\" + start + list + end;\n                textarea.selectionStart = start.length + list.length;\n                textarea.selectionEnd = textarea.selectionStart;\n                textarea.focus();\n");
      out.write("            }\n            if (e.key.toLowerCase() === 'tab') {\n                e.preventDefault();\n                if (e.shiftKey) {\n                    self.shiftTab(self);\n                }\n                else {\n                    self.addTab(self);\n                }\n            }\n        });\n        handlerOn = 1;\n\n    }\n    function addUnorderedList() {\n        var textarea = $(caseNote);\n        var start = textarea.value.substr(0, textarea.selectionStart);\n        var end = textarea.value.substr(textarea.selectionStart);\n        var list = \"- \";\n        var offset = 0;\n        if (textarea.selectionStart != textarea.selectionEnd) {\n            end = textarea.value.substr(textarea.selectionEnd);\n            var range = textarea.value.slice(textarea.selectionStart, textarea.selectionEnd);\n            list = \"\" + list + range.trim();\n        }\n        if (start.length && start[start.length - 1] != '\\n') {\n            list = \"\\n\" + list;\n        }\n        if (end.length && end[0] != '\\n') {\n            list = list + \"\\n\";\n");
      out.write("            offset = 1;\n        }\n        textarea.value = \"\" + start + list + end;\n        textarea.selectionStart = start.length + list.length - offset;\n        textarea.selectionEnd = textarea.selectionStart;\n        textarea.focus();\n        onListing = {\n            type: 'unordered'\n        };\n    };\n    function addOrderedList() {\n        var textarea = $(caseNote);\n        var start = textarea.value.substr(0, textarea.selectionStart);\n        var end = textarea.value.substr(textarea.selectionStart);\n        var list = \"1. \";\n        var offset = 0;\n        if (textarea.selectionStart != textarea.selectionEnd) {\n            end = textarea.value.substr(textarea.selectionEnd);\n            var range = textarea.value.slice(textarea.selectionStart, textarea.selectionEnd);\n            list = \"\" + list + range.trim();\n        }\n        if (start.length && start[start.length - 1] != '\\n') {\n            list = \"\\n\" + list;\n        }\n        if (end.length && end[0] != '\\n') {\n            list = list + \"\\n\";\n            offset = 1;\n");
      out.write("        }\n        textarea.value = \"\" + start + list + end;\n        textarea.selectionStart = start.length + list.length - offset;\n        textarea.selectionEnd = textarea.selectionStart;\n        textarea.focus();\n        onListing = {\n            type: 'ordered',\n            number: 2,\n        };\n    };\n\n// Smart Template code\nvar smartTmplVM = {\n    STATE: {\n        TRAVERSING: \"TRAVERSING\",\n        SELECTED_PLACEHOLDER_TEXT: \"SELECTED_PLACEHOLDER_TEXT\",\n        SELECTED_OPTION_TEXT: \"SELECTED_OPTION_TEXT\"\n    },\n    TMPL_DELIM_START: '<',\n    TMPL_DELIM_END: '>',\n    TMPL_DELIM_CHOICE: '|',\n    TMPL_PLACEHOLDER_CHAR: '?'\n}\n// Â«Â»\nvar smartTmpl = (function () {\n    function init(el) {\n        if (!el) {\n            return;\n        }\n\n        el.addEventListener('click', function (event) {\n            var value = event.target.value;\n            if (!value) {\n                return;\n            }\n\n            var selection = getTextSelection(event.target);\n\n            var sectionStart = selection.start || 0;\n");
      out.write("            var i = sectionStart;\n            var sectionStartFound = false;\n            for (i = sectionStart; i > 0; --i) {\n                if (value[i - 1] === smartTmplVM.TMPL_DELIM_END) {\n                    return;\n                }\n                if (value[i - 1] === smartTmplVM.TMPL_DELIM_START) {\n                    sectionStart = i - 1;\n                    sectionStartFound = true;\n                    break;\n                }\n            }\n            if (!sectionStartFound) {\n                return;\n            }\n\n            var sectionEnd = sectionStart;\n            for (i = sectionStart; i < value.length; ++i) {\n                if (value[i + 1] === smartTmplVM.TMPL_DELIM_START) {\n                    return;\n                }\n                if (value[i + 1] === smartTmplVM.TMPL_DELIM_END) {\n                    sectionEnd = i + 2;\n                    break;\n                }\n            }\n\n            var section = value.substring(sectionStart, sectionEnd);\n            if (!section || section && !section.length) {\n");
      out.write("                return;\n            }\n\n            var choiceStart = selection.start;\n            for (i = selection.start; i >= sectionStart; --i) {\n                if (value[i - 1] ===  smartTmplVM.TMPL_DELIM_START || value[i - 1] === smartTmplVM.TMPL_DELIM_CHOICE) {\n                    choiceStart = i;\n                    break;\n                }\n            }\n\n            var choiceEnd = choiceStart;\n            for (i = choiceEnd; i <= sectionEnd; i++) {\n                if (value[i + 1] === smartTmplVM.TMPL_DELIM_END || value[i + 1] === smartTmplVM.TMPL_DELIM_CHOICE) {\n                    choiceEnd = i;\n                    break;\n                }\n            }\n\n            var choice = value.substring(choiceStart, choiceEnd + 1)\n            if (!choice || choice && !choice.length) {\n                return;\n            }\n\n            event.target.value = value.substring(0, sectionStart) + choice + value.substring(sectionEnd, value.length);\n        });\n\n        el.onkeydown = (event) => {\n            const value = event.target.value;\n");
      out.write("\n            // Proceed if \"tab\" or \"enter\" key is pressed\n            if (event.keyCode === 9 || event.keyCode === 13 ) {\n                let selectionStart = el.selectionStart;\n                let selectionEnd = el.selectionEnd;\n                if ( selectionEnd == selectionStart && event.keyCode === 13) { return; }\n                const highlighted = value\n                    .substring(selectionStart, selectionEnd)\n                    .trim();\n\n               // Check if a keyword is already highlighted\n                if (isHighlighting(el) && event.keyCode === 13) {\n                    // Check if highlighted a placeholder char or option text\n                    if (highlighted === smartTmplVM.TMPL_PLACEHOLDER_CHAR) {\n                        state = smartTmplVM.STATE.SELECTED_PLACEHOLDER_TEXT;\n                    } else {\n                        state = smartTmplVM.STATE.SELECTED_OPTION_TEXT;\n                    }\n                } else {\n                    state = smartTmplVM.STATE.TRAVERSING;\n                }\n");
      out.write("\n                switch (state) {\n                    case smartTmplVM.STATE.TRAVERSING: {\n                        // Find first index of placeholder char\n                        const placeholderCharIndex = findPlaceholderCharIndex(selectionEnd,value);\n\n                        // Find first index of option text\n                        const selectionTextIndex = findSelectionTextIndex(selectionEnd,value);\n\n						if (\n							placeholderCharIndex == -1 &&\n							selectionTextIndex.startIndex == -1 &&\n							selectionTextIndex.endIndex == -1\n							) {\n								// nothing found, so wrap to the top and check again\n								el.setSelectionRange(1,1);\n								const placeholderCharIndex = findPlaceholderCharIndex(0,value);\n								const selectionTextIndex = findSelectionTextIndex(0,value);\n							}\n                        // Highlight the next occurrence\n                        if (\n                            selectionTextIndex.startIndex !== -1 &&\n                            selectionTextIndex.endIndex !== -1\n                        ) {\n");
      out.write("                            if (\n                                selectionTextIndex.startIndex < placeholderCharIndex ||\n                                placeholderCharIndex === -1\n                            ) {\n                                el.setSelectionRange(\n                                    selectionTextIndex.startIndex,\n                                    selectionTextIndex.endIndex\n                                );\n                                state = smartTmplVM.STATE.SELECTED_OPTION_TEXT;\n                            } else {\n                                el.setSelectionRange(\n                                    placeholderCharIndex,\n                                    placeholderCharIndex +\n                                    smartTmplVM.TMPL_PLACEHOLDER_CHAR.length\n                                );\n                                state = smartTmplVM.STATE.SELECTED_PLACEHOLDER_TEXT;\n                            }\n                        } else if (placeholderCharIndex !== -1) {\n                            el.setSelectionRange(\n");
      out.write("                                placeholderCharIndex,\n                                placeholderCharIndex + smartTmplVM.TMPL_PLACEHOLDER_CHAR.length\n                            );\n                            state = smartTmplVM.STATE.SELECTED_PLACEHOLDER_TEXT;\n                        }\n						// scroll to selection\n						el.blur();\n						el.focus();\n                        break;\n                    }\n\n                    case smartTmplVM.STATE.SELECTED_PLACEHOLDER_TEXT: {\n                        // Replace highlighted placeholder text\n                        if (highlighted === smartTmplVM.TMPL_PLACEHOLDER_CHAR) {\n                            const updatedValue =\n                                value.substring(0, selectionStart) +\n                                \"\" +\n                                value.substring(selectionEnd, value.length);\n                            event.target.value = updatedValue;\n							if (value.length == selectionEnd) { selectionEnd = 0; } //ensure the end of value end case doesn't break\n");
      out.write("                            el.setSelectionRange(selectionEnd+1, selectionEnd+1);  \n                        }\n\n                        break;\n                    }\n\n                    case smartTmplVM.STATE.SELECTED_OPTION_TEXT: {\n                        // Replace entire selection options with the highlighted option text\n                        selectionStart--;\n\n                        selectionEnd = value\n                            .substring(selectionStart, value.length)\n                            .indexOf(smartTmplVM.TMPL_DELIM_END);\n                        if (selectionEnd !== -1) {\n                            selectionEnd += selectionStart + 1;\n							selectionStart = value.lastIndexOf(smartTmplVM.TMPL_DELIM_START,selectionEnd);\n\n                            const updatedValue =\n                                value.substring(0, selectionStart) +\n                                highlighted +\n                                value.substring(selectionEnd, value.length);\n                            event.target.value = updatedValue;\n");
      out.write("                            el.setSelectionRange(selectionStart, selectionStart);\n                        }\n\n                        break;\n                    }\n\n                    default: {\n                        break;\n                    }\n                }\n\n                event.preventDefault();\n                event.stopPropagation();\n            } else {\n                state = smartTmplVM.STATE.TRAVERSING;\n            }\n        }\n    }\n\n    // Return selected text\n    function getTextSelection(el) {\n        var start = 0, end = 0, normalizedValue, range,\n            textInputRange, len, endRange;\n\n        if (typeof el.selectionStart == \"number\" && typeof el.selectionEnd == \"number\") {\n            start = el.selectionStart;\n            end = el.selectionEnd;\n        } else {\n            range = document.selection.createRange();\n\n            if (range && range.parentElement() == el) {\n                len = el.value.length;\n                normalizedValue = el.value.replace(/\\r\\n/g, \"\\n\");\n\n                textInputRange = el.createTextRange();\n");
      out.write("                textInputRange.moveToBookmark(range.getBookmark());\n\n                endRange = el.createTextRange();\n                endRange.collapse(false);\n\n                if (textInputRange.compareEndPoints(\"StartToEnd\", endRange) > -1) {\n                    start = end = len;\n                } else {\n                    start = -textInputRange.moveStart(\"character\", -len);\n                    start += normalizedValue.slice(0, start).split(\"\\n\").length - 1;\n\n                    if (textInputRange.compareEndPoints(\"EndToEnd\", endRange) > -1) {\n                        end = len;\n                    } else {\n                        end = -textInputRange.moveEnd(\"character\", -len);\n                        end += normalizedValue.slice(0, end).split(\"\\n\").length - 1;\n                    }\n                }\n            }\n        }\n\n        return {\n            start: start,\n            end: end\n        }\n    }\n\n    // Return if a keyword is highlighted\n    function isHighlighting(el) {\n        return el.selectionStart !== el.selectionEnd;\n");
      out.write("    }\n\n    // Return index of placeholder char\n    function findPlaceholderCharIndex(selectionEnd,value) {\n        if (!value || (value && !value.length)) {\n            return -1;\n        }\n        return value.indexOf(smartTmplVM.TMPL_PLACEHOLDER_CHAR,selectionEnd);  \n\n    }\n\n    // Return index of selection option text\n    function findSelectionTextIndex(selectionEnd,value) {\n        let startIndex = -1;\n        let endIndex = -1;\n\n        if (!value || (value && !value.length)) {\n            return {\n                startIndex,\n                endIndex\n            };\n        }\n\n        try {\n            startIndex = value.indexOf(smartTmplVM.TMPL_DELIM_START,selectionEnd);\n            var startIndex2 = value.indexOf(smartTmplVM.TMPL_DELIM_CHOICE,selectionEnd); \n       \n            if (startIndex == -1) { startIndex = startIndex2; }\n            if (startIndex !== -1) {\n                if (startIndex > startIndex2) { //there is a delimiter that should start the selection\n                    startIndex = startIndex2;\n");
      out.write("                    endIndex = value\n                        .substring(startIndex, value.length)\n                        .indexOf(smartTmplVM.TMPL_DELIM_END);\n                    if (endIndex !== -1) {\n                        endIndex += startIndex + 1;\n                    }\n\n                } else {\n                    endIndex = value\n                        .substring(startIndex, value.length)\n                        .indexOf(smartTmplVM.TMPL_DELIM_END);\n                    if (endIndex !== -1) {\n                        endIndex += startIndex + 1;\n                    }\n\n                }\n            }\n\n            if (startIndex !== -1 && endIndex !== -1) {\n                startIndex++;\n\n                const substring = value.substring(startIndex, endIndex);\n                if (substring && substring.includes(smartTmplVM.TMPL_DELIM_CHOICE)) {\n                    endIndex = substring.indexOf(smartTmplVM.TMPL_DELIM_CHOICE);\n                } else if (substring) {\n                    endIndex = substring.indexOf(smartTmplVM.TMPL_DELIM_END);\n");
      out.write("                }\n\n                if (endIndex !== -1) {\n                    endIndex += startIndex;\n                }\n            }\n\n        } catch (error) { }\n\n        return {\n            startIndex,\n            endIndex\n        };\n    }\n\n    return {\n        init: init\n    }\n})();	\n\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /casemgmt/newEncounterLayout.js.jsp(27,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /casemgmt/newEncounterLayout.js.jsp(27,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/casemgmt/newEncounterLayout.js.jsp(27,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /casemgmt/newEncounterLayout.js.jsp(27,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setScope("request");
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /casemgmt/newEncounterLayout.js.jsp(49,9) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
